### ISSUE TITLE
💡 [REQUEST] - <微调功能>

### ISSUE THREAD

**Issue by lj163ucas** [QwenLM/Qwen-VL#1]
### 摘要 | Summary

请问如何针对下游图文创作的细分任务做微调，能否开源微调教程？应该用Qwen-VL还是Qwen-VL-Chat？

### 基本示例 | Basic Example

RT

### 缺陷 | Drawbacks

促进社区发展

**Comment by simonJJJ** [comment]
Hi @lj163ucas, we have supported the fine-tuning scripts, please follow this [link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh).

**Comment by Syno8** [comment]
你好，你的链接已经打不开了 @simonJJJ
