### ISSUE TITLE
[eval_mm GQA jsonl request] The download url of GQA jsonl files seem wrong, could you please provide the right version?

### ISSUE THREAD

**Issue by HiHippie** [QwenLM/Qwen-VL#104]
It seems that the train jsonl is 'train.jsonl' and the test jsonl is 'testdev_balanced.jsonl', but the download urls provide 'test_balanced.jsonl' and 'train_balanced.json'.  Besides, the 'test_balanced.jsonl' has no annotations for the accuracy metric.

thx

**Comment by zdxff** [comment]
I have the same request. The gqa test path in evaluate_vqa is 'testdev_balanced.jsonl' but provide 'test_balanced.jsonl'. Can anyone provide the true download url? I will be extremely grateful.

**Comment by vealocia** [comment]
Hi @HiHippie and @zdxff, sorry for the late reply and thanks for you to point this mistake in download link.
We have just corrected the download link.

**Comment by zdxff** [comment]
Thank you for your help!
