### ISSUE TITLE
[BUG] <Unable to load model from local>

### ISSUE THREAD

**Issue by TongLi97** [QwenLM/Qwen-VL#106]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

# I have manually downloaded all the files in the Qwen/Qwen-VL-Chat path on HuggingFace and saved them locally.
And changed "Qwen/Qwen-VL-Chat" in the source code to the file path, but it could not be loaded successfully. What causes this?

# tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True) 
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cuda", trust_remote_code=True).eval()
# model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
Can you provide error information? The local path requires an absolute path.

**Comment by TongLi97** [comment]
I used the absolute path "/mypath/Qwen/Qwen-VL-Chat/". And I made sure that I manually downloaded the files of HuggingFace "Qwen/Qwen-VL-Chat" locally.
The error message is as follows, it seems that the class cannot be found:
**************************************
Traceback (most recent call last):
tokenizer = AutoTokenizer.from_pretrained('/mypath/Qwen/Qwen-VL-Chat/')
   File "/mypath/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
     raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.
***************************************
By the way, is this related to the parameter "trust_remote_code=True"?

**Comment by ShuaiBai623** [comment]
Yes, the parameter `trust_remote_code=True` should be added. 
tokenizer = AutoTokenizer.from_pretrained('/mypath/Qwen/Qwen-VL-Chat/',trust_remote_code=True)
`trust_remote_code=True` means that this model code to be downloaded and run from the hub.

**Comment by TongLi97** [comment]
But I followed the tutorial on offline mode on the HuggingFace official website (https://huggingface.co/docs/transformers/installation#offline-mode).
It doesn't seem to use "trust_remote_code=True" anymore.
************************************
1. Use the [PreTrainedModel.from_pretrained()] and [PreTrainedModel.save_pretrained()] workflow:
Download your files ahead of time with [PreTrainedModel.from_pretrained()]:
>>from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
>>tokenizer = AutoTokenizer.from_pretrained("bigscience/T0_3B")
>>model = AutoModelForSeq2SeqLM.from_pretrained("bigscience/T0_3B")

2. Save your files to a specified directory with [PreTrainedModel.save_pretrained()]:
>>tokenizer.save_pretrained("./your/path/bigscience_t0")
>>model.save_pretrained("./your/path/bigscience_t0")

3. Now when you’re offline, reload your files with [PreTrainedModel.from_pretrained()] from the specified directory:
>>tokenizer = AutoTokenizer.from_pretrained("./your/path/bigscience_t0")
>>model = AutoModel.from_pretrained("./your/path/bigscience_t0")
************************************

**Comment by TongLi97** [comment]
It seems that "trust_remote_code=True" must be used, despite trying to load from local.

**Comment by yangyijune** [comment]
My solution:

```from transformers.generation import GenerationConfig
import torch
torch.manual_seed(77)

# Note: The default behavior now has injection attack prevention off.
tokenizer = QWenTokenizer.from_pretrained("/bian_data/qwen-VL/Qwen-VL-Chat", trust_remote_code=False)```
