### ISSUE TITLE
[BUG] <title>无法正确加载lora微调后的模型

### ISSUE THREAD

**Issue by xyw7** [QwenLM/Qwen-VL#107]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-VL/assets/58246533/de4cfb82-2fe6-42e9-9d3f-f70febc10250)
如图所示，我根据readme中lora方法微调后 并且merge了模型，但是加载微调后模型的时候显示AutoTokenizer加载有问题

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
lora之后的模型需要特别的load方式，或者合并参数后在进行正常load，可以参照[Finetuning](https://github.com/QwenLM/Qwen-VL#finetuning)的最后部分
```python
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()

merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
merged_model.save_pretrained(new_model_directory, max_shard_size="2048MB", safe_serialization=True)
```

**Comment by PangziZhang523** [comment]
楼主解决了嘛，也是merge完以后，推理提示AutoTokenizer加载有问题

**Comment by xyw7** [comment]
> 楼主解决了嘛，也是merge完以后，推理提示AutoTokenizer加载有问题

我后来就tokenizer直接指定原来的官方路径 模型加载自己微调的。但好像微调的数据结构构建的不太好，效果还不如原来的模型。。

**Comment by CrazyBrick** [comment]
> > 楼主解决了嘛，也是merge完以后，推理提示AutoTokenizer加载有问题
> 
> 我后来就tokenizer直接指定原来的官方路径 模型加载自己微调的。但好像微调的数据结构构建的不太好，效果还不如原来的模型。。

楼主用了多少数据呢

**Comment by Cristhine** [comment]
> > 楼主解决了嘛，也是merge完以后，推理提示AutoTokenizer加载有问题
> 
> 我后来就tokenizer直接指定原来的官方路径 模型加载自己微调的。但好像微调的数据结构构建的不太好，效果还不如原来的模型。。

请问怎么指定的 方便发一下不 我把原来路径的tokenizer拷贝好像也没用

**Comment by elesun2018** [comment]
![image](https://github.com/QwenLM/Qwen-VL/assets/37207093/8add532e-8017-42f6-bd52-5ae6637b2b37)
