### ISSUE TITLE
Is Qwen-VL-Chat-1.1  available now? 

### ISSUE THREAD

**Issue by cwfxcz** [QwenLM/Qwen-VL#114]
I have tried to download the Qwen-VL-Chat model from modelscope and notice that it shows the lastest version is 1.0.3. Since Qwen-VL-Chat-1.1 has greater capability of Chinese instruction-following, is there any chance we can try it?

**Comment by ShuaiBai623** [comment]
Currently the lastest version model on modelscope is Qwen-VL-Chat-1.1.
