### ISSUE TITLE
[BUG] <title> invalid syntax

### ISSUE THREAD

**Issue by doraemon-plus** [QwenLM/Qwen-VL#119]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行sh finetune/finetune_lora_single_gpu.sh报错：
File “finetune.py", line 25
    model_name_or_path: Optional[str] = field(default="Qwen/Qwen-7B")
SyntaxError: invalid syntax

### 运行环境 | Environment

```Markdown
- OS:
- Python: 3.8.17
- Transformers: 4.32.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by ShuaiBai623** [comment]
这边测试是没有问题，是否是路径名有字符问题或者修改了什么地方

**Comment by doraemon-plus** [comment]
没有修改过finetune.py文件，我把finetune_lora_single_gpu.sh里的”python finetune.py“改成"python3 finetune.py"就好了，但是报了个跟#120一样的错：RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

**Comment by jinze1994** [comment]
invalid syntaxmodel_name_or_path: Optional[str]
