### ISSUE TITLE
💡 [REQUEST] - <支持finetune>

### ISSUE THREAD

**Issue by dengfenglai321** [QwenLM/Qwen-VL#12]
### 摘要 | Summary

是否有计划支持微调？

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by simonJJJ** [comment]
Hi @dengfenglai321, we have supported the finetune scripts, please follow this [link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh).

**Comment by rujews** [comment]
> Hi @dengfenglai321, we have supported the finetune scripts, please follow this [link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh).

   请问这种微调方式，可以让Qwen-VL-Chat学会新的图片的解读、位置定位等能力吗？因为有些业务需求的图片，Qwen-VL并不认识。
@simonJJJ

**Comment by dengfenglai321** [comment]
> Hi @dengfenglai321, we have supported the finetune scripts, please follow this [link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh).

谢谢，是否可以给出一些微调的数据集格式例子，比如图像 - 文本是怎么组织的

**Comment by Ashwath-Shetty** [comment]
is anyone able to finetune? if yes, how? any tutorials or documentations? @rujews @dengfenglai321 @simonJJJ

**Comment by huohuotm** [comment]
https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/lora_ddp/sft.sh

**Comment by ShuaiBai623** [comment]
Now we provide the official training script (full parameters, LoRA, QLoRA), finetune.py, for users to finetune the pretrained model for downstream applications in a simple fashion. Please refer to [Finetuning](https://github.com/QwenLM/Qwen-VL#finetuning)
