### ISSUE TITLE
[BUG] <title> Watchdog caught collective operation timeout: WorkNCCL(SeqNum=923, OpType=REDUCE, Timeout(ms)=1800000) ran for 1806745 milliseconds before timing out.

### ISSUE THREAD

**Issue by AlexXx-Wu** [QwenLM/Qwen-VL#121]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

8张a100-80g 复现 finetune_ds.sh 报错 
NCCL INFO comm 0x8312280 rank 7 nranks 8 cudaDev 7 busId c9000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=923, OpType=REDUCE, Timeout(ms)=1800000) ran for 1806745 milliseconds before timing out.

### 运行环境 | Environment

```Markdown
- OS: 
- Python:3.9
- Transformers:4.32.0
- PyTorch:1.13.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by AlexXx-Wu** [comment]
> 重跑还会出现这个问题吗

稳定复现，当前训练集包括图文和纯文本多轮对话数据混合，但是测试了下其他场景，多卡的纯文本数据集可以跑通，单卡lora的图文和纯文本多轮对话数据集可以跑通，不知怎么归因:(

**Comment by ShuaiBai623** [comment]
如果是纯文本和多模态数据一起训练的话，需要引入fake image，请看下模型文件有没有同步到huggface的最新版，https://huggingface.co/Qwen/Qwen-VL-Chat/commit/bbe5a805de49a41b7343d240ab84d4c305caa265，希望能解决您的问题！

**Comment by Junphy-Jan** [comment]
修改之后仍然出现这个问题。

inputs_embeds = inputs_embeds + image_embeds.mean()*0
——————
这里 image_embeds 的shape 是 (b, 256, 4096) mean()*0 算了下好像就是直接+0？
能否解释图文混合训练时这里，image 为None 为什么 需要加一下 fake image么
感谢

**Comment by ShuaiBai623** [comment]
是为了针对分布式并行有的参数没梯度造成错误等待的问题

**Comment by AlexXx-Wu** [comment]
> 是为了针对分布式并行有的参数没梯度造成错误等待的问题

modeling是最新的，现在看是在运行了几个step后卡住，在执行成功的steps中，存在混合的图文数据，感觉fake image不是卡点，而且现在测试的话多卡lora也是可以跑通的

**Comment by Junphy-Jan** [comment]
试了 ZeRO stage 1是可以的，Stage 2就会在 all_reduce 的时候卡住

**Comment by ShuaiBai623** [comment]
主要是针对多模态和纯文本一起训会有这个问题，可以先用 ZeRO stage 1，ZERO2的问题正在解

**Comment by ShuaiBai623** [comment]
问题原因 forward 过程使用的参数顺序不一致，进而 backward 时 parameter ready 的顺序不一致，因此通信的时候卡住导致报错，可以参照 https://huggingface.co/Qwen/Qwen-VL/commit/616d8e007c3ec9f65d3a020c6a638d0c3bf2e7ec 进行修改或者直接同步huggface最新代码

**Comment by wen2cheng** [comment]
该修复针对stage2可以跑通，但是stage3的时候依然会卡主不动

**Comment by Luccadoremi** [comment]
> 该修复针对stage2可以跑通，但是stage3的时候依然会卡主不动

请问stage3 问题解决了吗？
