### ISSUE TITLE
IMG_TOKEN_SPAN = 256，这个值能调大一点吗，如果用的是腾讯云cos的签名地址就会超过这个长度

### ISSUE THREAD

**Issue by 18827555809** [QwenLM/Qwen-VL#122]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
这同时表示img token被压缩的长度，直接调大会有问题，建议先可以将文件先转存下保存为适度长度的图片文件名，后续我们会支持长的文件名和byte类型

**Comment by 18827555809** [comment]
image = tokenizer.draw_bbox_on_latest_picture(response, history)这个方法是否调用是不是根据response 的</box>标签来判断的？比如：<ref>"击掌"</ref><box>(211,412),(577,891)</box>

**Comment by ShuaiBai623** [comment]
是的，是判断结果里的box标签
