### ISSUE TITLE
请问模型可不可以只接收文本输入，像普通LLM那样对话？Demo里我看到是可以的

### ISSUE THREAD

**Issue by WilTay1** [QwenLM/Qwen-VL#128]

**Comment by WeiXuanLi-1024** [comment]
可以的

**Comment by jinze1994** [comment]
Qwen-VL可以作为正常LLM使用，我们也评测了纯文本能力的表现，结果可以参考 issue #23 .
具体讨论可以参考最新Paper：
![纯文本能力](http://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/jinze.bjz/others/20231020121023.jpg)
