### ISSUE TITLE
Qwen-VL似乎更容易输出否定的答案

### ISSUE THREAD

**Issue by Ivesfu** [QwenLM/Qwen-VL#129]
在我的实际测试中，发现Qwen-VL更容易输出类似“There is no existence of ”的否定答案。请问Qwen-VL是做了什么特殊的操作和处理吗？
<img width="868" alt="image" src="https://github.com/QwenLM/Qwen-VL/assets/57118912/945474bd-b15c-4b70-af0c-61c51f1c37ea">

**Comment by jinze1994** [comment]
Good observation. Qwen-VL在SFT数据中加入了对抗样本，用来预防文本对图片内容的恶意引导。在以上例子中，Qwen-VL认为鸵鸟不在running，而是在standing。因此上述回答主要强调 no existence of ostrich **running**。

用以下例子可以看出，模型知道鸵鸟在水里。但没有理解您的主要问题关注点在“鸵鸟在哪里”，而是过于关注“鸵鸟在干什么”了。平衡对齐能力和防止恶意引导是一个 non-trivial 的问题，我们会继续努力优化模型。

![20231020142009](https://github.com/QwenLM/Qwen-VL/assets/13191886/d6d1ef6a-dde9-4b76-abbd-6a6353bebec8)

![lQLPJx_YjvBZk4TNA_rNBAawNkwsIMN0CoUFJHKBJ0C2AA_1030_1018](https://github.com/QwenLM/Qwen-VL/assets/13191886/d400cbde-26e6-4e07-8cbe-dfc9fd2212d7)

![20231020142122](https://github.com/QwenLM/Qwen-VL/assets/13191886/8b26aebb-071d-48dd-9f2f-39194f2c30f1)
