### ISSUE TITLE
[BUG] <title>加减法都能做错，离了个大谱！

### ISSUE THREAD

**Issue by wuzhongyuan** [QwenLM/Qwen-VL#13]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![f4a1ecf9d56d716585a6a3ddb4db989](https://github.com/QwenLM/Qwen-VL/assets/14008924/40d0139b-9541-40ee-9516-8f5e64a1c929)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by liaoweiguo** [comment]
这问题很常见
