### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by abbhay** [QwenLM/Qwen-VL#131]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![1698025990986](https://github.com/QwenLM/Qwen-VL/assets/36267615/34215cfd-7ff7-412b-b4e2-c896568fe013)
对图片框选报错。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
这个应该是缺少字体文件的问题，可以把仓库里的[SimSun.ttf](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/SimSun.ttf)放到对应目录
