### ISSUE TITLE
我可以在不改变模型参数的情况下增加special tokens吗？

### ISSUE THREAD

**Issue by ricardo-young-ui** [QwenLM/Qwen-VL#133]
你好，首先感谢Qwen-VL出色的工作。我在应用时遇到了一些疑问。在<img><box>等预设的special tokens之外，我想针对自己的任务增加新的special tokens以微调特定的任务，但这似乎会改变字典长度，影响到lm_head层的参数加载。是否有一种方式可以让我即增加新的special tokens同时可以完整的加载预训练参数呢？

**Comment by ShuaiBai623** [comment]
可以参考qwen tokenizer里添加special tokens的方式添加，https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/tokenization_qwen.py#:~:text=self.IMAGE_ST%20%3D%20(,%7D

**Comment by jinze1994** [comment]
可以直接复用这几个token：

**Comment by momoiu2** [comment]
> 可以自己新增；也可以直接复用这几个extra tokens，这几个extra token没有被训练到：https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/tokenization_qwen.py#L44

那wte和lm_head需要训练吗

**Comment by ShuaiBai623** [comment]
需要
