### ISSUE TITLE
MME benchmark中OCR分数很低

### ISSUE THREAD

**Issue by Iriya99** [QwenLM/Qwen-VL#134]
你好，非常感谢qwen-VL杰出的工作！在使用qwen-VL-chat跑MME benchmark时，我注意到结果中OCR得分只有72.5，远低于 https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/Evaluation/README.md 中的140.00分，请问是什么原因导致的呢？
![image](https://github.com/QwenLM/Qwen-VL/assets/106980564/aa1fde86-83ac-4465-a480-ed492afba520)

**Comment by ShuaiBai623** [comment]
我们的1.0模型对应MME benchmark上的分数，在1.1版本的模型可能存在差异，由于mme采用yes/no的判断题来测试，这里会存在对prompt不稳定的情况，并不一定能真实反映对话中ocr能力，建议以实际体验为准
