### ISSUE TITLE
[BUG] <title>lora单机多卡训练报错：torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by doraemon-plus** [QwenLM/Qwen-VL#138]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

torchrun --nproc_per_node 4 --nnodes 1 finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --fix_vit True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --report_to "none" \
    --model_max_length 3000 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed finetune/ds_config_zero2.json

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.8
- Transformers:4.32
- PyTorch:2.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local rank: 0 (pid: 2548) of binary: /opt/conda/bin/python3

**Comment by ShuaiBai623** [comment]
能提供更详细的信息吗，以及huggingface上的模型文件是否同步到最新。

**Comment by doraemon-plus** [comment]
![ME1698826212163](https://github.com/QwenLM/Qwen-VL/assets/55863674/04eaeec7-d14e-4f85-827e-d062763d1cbc)

**Comment by peace-zy** [comment]
> ![ME1698826212163](https://usercontent.githubfast.com/private-user-images/55863674/279614454-04eaeec7-d14e-4f85-827e-d062763d1cbc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzkwMzYsIm5iZiI6MTcwMTEzODczNiwicGF0aCI6Ii81NTg2MzY3NC8yNzk2MTQ0NTQtMDRlYWVlYzctZDE0ZS00Zjg1LTgyN2UtZDA2Mjc2M2QxY2JjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAyMzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTJlZTIwYWI3NmNjZTlkNzhiZTFkMTYzMTNhMzVlYzM3MmYzOTJlZDFlNDZlNWMzYzE5Zjg5MjExZTgxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MuLSYcd9_SHodvyE6Em4tBltZ8behJV0OxcqwLEgWvQ)

您好，遇到了同样的问题，您解决了吗

**Comment by HUOUO7** [comment]
是不是model_max_length设置太大了？

**Comment by ljjcoder** [comment]
@doraemon-plus遇到同样的问题，请问你是如何解决的？

**Comment by wudidaxuexue** [comment]
请问怎么解决的？遇到了相同的问题

**Comment by chuangzhidan** [comment]
> --fix_vit 改为false就报错，请问是什么原因哈？谢谢
