### ISSUE TITLE
[BUG] <title>模型进行多次推理后，输出变差

### ISSUE THREAD

**Issue by waltonfuture** [QwenLM/Qwen-VL#139]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如果我只进行一次推理，可以得到不错的输出：
![image](https://github.com/QwenLM/Qwen-VL/assets/98318797/087ace1c-8098-4a49-89e7-15755a55b49e)

![image](https://github.com/QwenLM/Qwen-VL/assets/98318797/7a8f9fe4-d023-434a-a10c-23947ace312a)

如果我进行多次推理，那么输出会有问题（内容缺失）：
![image](https://github.com/QwenLM/Qwen-VL/assets/98318797/b946a5cb-6c37-4dcc-8aa5-882ae977e8f2)

![image](https://github.com/QwenLM/Qwen-VL/assets/98318797/2770501a-ae1d-4556-a4bd-ac24fcc2a2ea)

### 期望行为 | Expected Behavior

请问这种偏差是什么原因造成的呢？该如何解决呢？

### 运行环境 | Environment

```Markdown
运行环境正常
```

**Comment by 2132660698** [comment]
是不是因为多轮对话上下文的原因？

**Comment by WeiXuanLi-1024** [comment]
也有可能是模型重复输出惩罚

**Comment by ShuaiBai623** [comment]
这个应该是随机性造成的，保持一致可以设置top_p为0.01
