### ISSUE TITLE
Questions about training data

### ISSUE THREAD

**Issue by guokr233** [QwenLM/Qwen-VL#14]
1. What type of in-house data is used in the pre-training phase?
2. In the Multi-task Pre-training stage, OCR data is used, including SynthDoG-en & zh, Common Crawl pdf & HTML. How is Common Crawl pdf & HTML obtained? Which dataset is it from or is it made by yourself? If it is made by yourself, how is it done?

Thanks for your work!

**Comment by tinytangent** [comment]
Common Crawl pdfs are obtained from https://digitalcorpora.org/corpora/file-corpora/cc-main-2021-31-pdf-untruncated, which is indicated on page 6, footnote 3 of the paper.

**Comment by simonJJJ** [comment]
Hi @guokr233, the In-house data is just image-text pairs.
