### ISSUE TITLE
[BUG] 2卡A100(80G)全参数训练 OOM，这个该怎么解决，如何对模型切分到两个卡上

### ISSUE THREAD

**Issue by mxsurui** [QwenLM/Qwen-VL#141]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

2卡A100(80G)全参数训练 OOM，这个该怎么解决，如何对模型切分到两个卡上

### 运行环境 | Environment

```Markdown
- OS:
- Python: Python 3.10.12 
- Transformers:transformers==4.32.0
- PyTorch: torch==2.0.1+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.3
- transformers-stream-generator 0.0.4
- x-transformers                0.15.0
```

**Comment by liangshaopeng** [comment]
目前我看只支持deepspeed ，如果是zero2 ，2卡A100粗算是不够的。 我大致算了下，需要4卡。

**Comment by njucckevin** [comment]
@liangshaopeng 请问是什么意思哇，80G A100不能直接全参数微调吗？谢谢~
