### ISSUE TITLE
hi is all the datasets used in qwen-vl applicable for commercial license 

### ISSUE THREAD

**Issue by papasanimohansrinivas** [QwenLM/Qwen-VL#145]
we want to put qwen-vl to commercial use and hence requesting to confirm or acknowledge that qwen-vl is trained on commercial optionable licenses ! @ichaobuster @tinytangent @JianxinMa @jinze1994 @yangapku

**Comment by jinze1994** [comment]
We welcome your commercial use of Qwen-VL.Qwen-VL uses a business-friendly open protocol that is free for personal, research, and small-scale commercial use, with licensing required only for commercial use over 100 million monthly lives.

**Comment by jinze1994** [comment]
Qwen-VL uses a business-friendly open protocol that is free for personal, research, and small-scale commercial use, with licensing required only for commercial use over 100 million monthly lives. You are welcome to contact us for more discussion.
