### ISSUE TITLE
[BUG] finetune代码中，没有看到任何读取图片的逻辑？

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen-VL#147]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如何读取图片，想知道数据集的基本格式。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
读图片的逻辑在模型文件中，可以参考https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/visual.py#:~:text=def%20encode(,return%20self(images)

**Comment by lucasjinreal** [comment]
@ShuaiBai623  Hi, 那么数据集的格式应该如何输入？貌似没有看到如何从json里面读取image_path的逻辑。

**Comment by TobiasLee** [comment]
> @ShuaiBai623 Hi, 那么数据集的格式应该如何输入？貌似没有看到如何从json里面读取image_path的逻辑。

https://huggingface.co/Qwen/Qwen-VL/blob/main/modeling_qwen.py#L559 这里image path 从 input_ids 里拿出来，然后在上面 @ShuaiBai623  的那里进行了 encode？ 但我有点不太明白的是这里 image path 也会被 tokenize 成 input_ids 吗？

**Comment by lucasjinreal** [comment]
@TobiasLee 有 dataset json的例子吗？如果是直接从content里面读取image_path，是怎么通过tag来标记的？

**Comment by TobiasLee** [comment]
https://github.com/QwenLM/Qwen-VL#data-preparation 这里有一个例子哈，看代码是提取 `<img>PATH_TO_ IMAGE/URL_TO_IMAGE</img>` 之间的内容作为 URL/File Path 来访问图片的

**Comment by SidHard** [comment]
@TobiasLee 您好，qwen最多支持几张图片呀。我的输入是视频的四张切帧+视频标题，可以进行finetune吗

**Comment by ezyzzy** [comment]
> @TobiasLee 您好，qwen最多支持几张图片呀。我的输入是视频的四张切帧+视频标题，可以进行finetune吗

您好，请问现在有解决方案吗？我也有类似的输入格式。
