### ISSUE TITLE
QWenTokenizer 图片路径解析

### ISSUE THREAD

**Issue by Eikor** [QwenLM/Qwen-VL#148]
你好！感谢你们精彩的工作。
使用了QWen-VL过后我有如下两个问题：
1，我注意到QWenTokenizer 的词表是存储在qwen.tiktoken文件里的，同时QWenTokenizer 还承担了解析图片路径的功能，如果我想保留该功能，同时加载自定义的词表该如何操作呢，是否会考虑开源更详细的tiktoken文件处理代码？
2，QWen-VL使用256个vision query充当临时token编码图片路径，是否会考虑改用其他更灵活的方案？（如果考虑训练一组更小的vision query 的话势必会影响到地址解析的长度）

期待你们的回复，谢谢！🙏

**Comment by jinze1994** [comment]
感谢您的关注。
1. 关于Qwen-VL的Tokenzier，我们已经开源了所有[代码](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/tokenization_qwen.py)。如果您想保留Qwen的词表，可以根据源代码文件向后补充或复用 SpecialTokens（EXTRAS部分均可使用）；如果您想直接替换Qwen的词表，可以参考代码修改load词表的逻辑，保留其它VL处理代码。
2. Qwen-VL之所以使用256个token编码图片路径，是因为我们当时没有在Huggingface社区找到特别合适的 Interleaved 多模态接口，出于尽可能兼容QwenLM接口的考虑，我们直接将图片路径编码到了token里，这样避免了额外的参数传递。更完备的方式应该独立返回多模态（如图片）信息，但当时并没有找到比较通用的HF接口。如果您有更好的方案，我们欢迎您或其它任何有兴趣贡献这部分代码～
