### ISSUE TITLE
[BUG] 在输入英文问题后,会在输出的英文文本中夹杂着中文字符

### ISSUE THREAD

**Issue by AnnaYang2020** [QwenLM/Qwen-VL#150]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

样例如下, 输出”The image depicts a group of people\u8fd9\u4e9b\u5e74\u6765\u4eba\u4eec\u7684\u884c\u4e3a\u65b9\u5f0f\u53d1\u751f\u4e86\u5f88\u5927\u7684\u53d8\u5316, they are all looking at their cell phones, seemingly disconnected from their surroundings and from each other. The person in the water is reaching out for help, but no one in the group seems to notice or care. This image could be interpreted as a commentary on the increasing dependence on technology and the potential consequences of being constantly connected, such as being less connected to the people around us and to the world around us. It could also be seen as a warning against being so absorbed in our own digital lives that we ignore the needs of others.“

### 期望行为 | Expected Behavior

我尝试过 Qwen-VL-Chat Bot,发现并不会出现许多中文的情况

### 复现方法 | Steps To Reproduce

运行的是CLI Inference
python -m llava.serve.cli \
    --model-path liuhaotian/llava-v1.5-7b \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --load-4bit

### 运行环境 | Environment

```Markdown
- OS: Ubantu 2023
- Python:3.10.13
- Transformers:4.31.0
- PyTorch:2.0.1+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

我尝试过 Qwen-VL-Chat Bot,发现并不会出现许多中文的情况.这个问题是我运行出现的问题,还是模型本来就有,想请教规避的方法?非常感谢~

**Comment by jinze1994** [comment]
您这边似乎运行的是 llava-1.5-7b？
```
 python -m llava.serve.cli
--model-path liuhaotian/llava-v1.5-7b
```
如您所说，Qwen-VL-Chat Bot是正常的。那么您可以参考Bot的代码，我们开源在这里： https://modelscope.cn/studios/qwen/Qwen-VL-Chat-Demo/file/view/master/app.py
