### ISSUE TITLE
[BUG] <title> ValueError: Unclosed image token

### ISSUE THREAD

**Issue by mxsurui** [QwenLM/Qwen-VL#151]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

SFT中文的OCR任务，训练300 step的时候出现了这个错误
我检查了所有的 json 里面的数据，图片最后都是带有 `</img>` 的，这个问题改如何解决呢？
  
  报错内容：
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/tokenization_qwen.py", line 260, in tokenize
    return _replace_closed_tag(tokens, self.image_start_tag, self.image_end_tag, _encode_imgurl)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/tokenization_qwen.py", line 84, in _replace_closed_tag
    raise ValueError("Unclosed image token")
ValueError: Unclosed image token

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.8
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA: 11.4
```

**Comment by jinze1994** [comment]
这个错误表示特殊标签未闭合。除了要检查 `<img></img>`标签，还要检查以下所有特殊标签。避免在OCR的文本中有以下标签。参考代码：https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/tokenization_qwen.py#L112
```
        image_start_tag='<img>',
        image_end_tag='</img>',
        image_pad_tag='<imgpad>',
        ref_start_tag='<ref>',
        ref_end_tag='</ref>',
        box_start_tag='<box>',
        box_end_tag='</box>',
        quad_start_tag='<quad>',
        quad_end_tag='</quad>',
```
如果您的OCR文本中确实有上述标签，可以在Tokenzier初始化时，通过参数重新定义上述的 special tag string。

**Comment by mxsurui** [comment]
> 这个错误表示特殊标签未闭合。除了要检查 `<img></img>`标签，还要检查以下所有特殊标签。避免在OCR的文本中有以下标签。参考代码：https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/tokenization_qwen.py#L112
> 
> ```
>         image_start_tag='<img>',
>         image_end_tag='</img>',
>         image_pad_tag='<imgpad>',
>         ref_start_tag='<ref>',
>         ref_end_tag='</ref>',
>         box_start_tag='<box>',
>         box_end_tag='</box>',
>         quad_start_tag='<quad>',
>         quad_end_tag='</quad>',
> ```
> 
> 如果您的OCR文本中确实有上述标签，可以在Tokenzier初始化时，通过参数重新定义上述的 special tag string。

Thx

**Comment by TiantZhang** [comment]
有解决吗？

**Comment by mxsurui** [comment]
> 有解决吗？

已经解决了

**Comment by TiantZhang** [comment]
> > 有解决吗？
> 
> 已经解决了

您的问题是在构造训练数据时有未闭合的字符？请问推理过程中有这个问题嘛？

**Comment by mxsurui** [comment]
> > > 有解决吗？
> > 
> > 
> > 已经解决了
> 
> 您的问题是在构造训练数据时有未闭合的字符？请问推理过程中有这个问题嘛？

推理过程是不会出现这个问题的

**Comment by lovegit2021** [comment]
请问具体要怎么解决啊 @Strand2013

**Comment by Strand2013** [comment]
> 请问具体要怎么解决啊 [@Strand2013](https://github.com/Strand2013)

检查一下你的训练数据
