### ISSUE TITLE
[BUG] updated chat int4 weights in huggingface might be buggy

### ISSUE THREAD

**Issue by davidas1** [QwenLM/Qwen-VL#153]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

It seems that the weights were updated recently (i guess to version 1.1?), but one file did not get updated (model-00004-of-00005.safetensors). Is this OK? 
The results from the model seem to indicate it is not working as expected.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
Thank you for your reminder. model-00004-of-00005.safetensors is the parameters of ViT. It is frozen during the sft process, so the parameters have not changed.
