### ISSUE TITLE
[BUG] <title> 从box到ref的微调问题

### ISSUE THREAD

**Issue by ZJUTSong** [QwenLM/Qwen-VL#159]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

微调示例中只看到caption和ref输入box输出的，是否可以训练模型输入box输出ref呢？
如下数据构造方式：
{"id": "identity_6",
        "conversations": [
            {
                "from": "user",
                "value": "请描述图Picture 1: <img>/aaa.png</img>\n中<box>((4, 2), (994, 52))</box>区域中的内容"
            },
            {
                "from": "user",
                "value": "<ref>一栋蓝色的房子，房前站着一个女人</ref>"
            }
]}

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by 2132660698** [comment]
![image](https://github.com/QwenLM/Qwen-VL/assets/94035926/4c10ced1-d30b-4485-9b93-19b4243308d7)

**Comment by ShuaiBai623** [comment]
是可以的
