### ISSUE TITLE
关于blip2权重的问题

### ISSUE THREAD

**Issue by zdxff** [QwenLM/Qwen-VL#160]
我在阅读论文”Qwen-VL: A Frontier Large Vision-Language Model with Versatile Abilities“的时候发现你们使用了BLIP-2 (Vicuna-13B)的权重，但是在lavis和huggingface都找不到对应的下载方法，请问可以告诉我怎么下载吗？

**Comment by Hannahhhhhhhhhhhh** [comment]
请问你获得BLIP-2 (Vicuna-13B)的权重了嘛？

**Comment by zdxff** [comment]
> 请问你获得BLIP-2 (Vicuna-13B)的权重了嘛？

我直接使用了instructblip论文里面的指标了

**Comment by Hannahhhhhhhhhhhh** [comment]
> > 请问你获得BLIP-2 (Vicuna-13B)的权重了嘛？
> 
> 我直接使用了instructblip论文里面的指标

好滴，谢谢
