### ISSUE TITLE
Can you share the code for OCR data production and processing

### ISSUE THREAD

**Issue by GXYM** [QwenLM/Qwen-VL#163]
### 实现PR | Implementation PR

Can you share the code for OCR data production and processing

### 摘要 | Summary

Can you share the code for OCR data production and processing

### 基本示例 | Basic Example

Can you share the code for OCR data production and processing

### 缺陷 | Drawbacks

Can you share the code for OCR data production and processing

**Comment by ShuaiBai623** [comment]
There's no plan for OCR data production and processing. Please stay tuned :-)
