### ISSUE TITLE
[BUG] Download link for evaluation is not available.

### ISSUE THREAD

**Issue by Artanic30** [QwenLM/Qwen-VL#17]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Hi, thanks for your work.
The download links (https://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/QwenVL/xxxx) are not open to public.
I met this issue when downloading evaluation annotation files.

`--2023-08-27 08:37:44--  https://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/QwenVL/evaluation/vizwiz/vizwiz_val.jsonl
Resolving ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com (ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com)... 39.101.35.33
Connecting to ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com (ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com)|39.101.35.33|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-27 08:37:44 ERROR 403: Forbidden.`

Could you change the permission for the download links?

### 复现方法 | Steps To Reproduce

wget https://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/QwenVL/evaluation/nocaps/nocaps_val.json

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by vealocia** [comment]
Hi, @Artanic30. Thanks for your intest in our work.
The download links are fixed now, you can retry it!

**Comment by Artanic30** [comment]
Thanks for the quick reply, but the links are still unavailable.
`--2023-08-27 19:16:38--  https://ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com/QwenVL/evaluation/nocaps/nocaps_val.json
Resolving ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com (ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com)... 39.101.35.33
Connecting to ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com (ofasys-wlcb.oss-cn-wulanchabu.aliyuncs.com)|39.101.35.33|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-27 19:16:38 ERROR 403: Forbidden.
`

**Comment by vealocia** [comment]
The download links are updated in [evaluation instructions](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/EVALUATION.md), please follow the new links for all files.

**Comment by Artanic30** [comment]
It works. Thanks again.
