### ISSUE TITLE
微调过程中将目标检测坐标归一化到[0,1000)的原因？

### ISSUE THREAD

**Issue by ZhuangPeiyu** [QwenLM/Qwen-VL#170]
请问在微调过程中，制作训练数据的时候，将目标检测坐标归一化到0-1000的原因是啥？当训练的时候，图像的分辨率不是被缩放到448*448吗？而要求模型预测的坐标却是在0-1000之间，这样子模型真的能够学到图中不同目标的确切位置吗？

**Comment by ShuaiBai623** [comment]
这里的0-1000坐标是归一化后的结果，即(坐标值/图像长宽)*1000,是一种相对坐标的表示

**Comment by chuangzhidan** [comment]
最终训练的也是让模型去预测448*448下的相对坐标？

**Comment by chuangzhidan** [comment]
最终训练的也是让模型去预测448*448下的相对坐标？
