### ISSUE TITLE
[BUG] Repetitive descriptions of input images

### ISSUE THREAD

**Issue by paulgavrikov** [QwenLM/Qwen-VL#175]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-VL-Chat sometimes generates highly repetitive and seemingly endless descriptions for images. E.g.,
_Prompt:_ Describe the image. 

_Response:_ In the image there are many different bottles of alcohol. 
There are at least 12 different bottles of alcohol visible. 
The image is a collage of different pictures of alcohol. 
The collage is made up of at least 12 different pictures. 
The collage is very colorful. 
The bottles are displayed on a shelf. 
The collage is made up of different sizes of bottles. 
The collage is made up of different shapes of bottles. 
The collage is made up of different colors of bottles. 
The collage is made up of different brands of bottles. 
The collage is made up of different sizes of pictures. 
The collage is made up of different shades of pictures. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color. 
The collage is made up of different shades of light. 
The collage is made up of different shades of dark. 
The collage is made up of different shades of color

### 期望行为 | Expected Behavior

Normal response.

### 复现方法 | Steps To Reproduce

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch

torch.manual_seed(0)

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cuda", trust_remote_code=True).eval()

query = tokenizer.from_list_format([
                {'image': 'image.png'},
                {'text': 'Describe the image.'},
          ])
inputs = tokenizer(query, return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
response = tokenizer.decode(pred.cpu()[0], skip_special_tokens=False)

```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.10
- Transformers: 4.34.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by ShuaiBai623** [comment]
The model may be Repetitive, which can be alleviated by setting  Repetition_penalty=1.2
