### ISSUE TITLE
请追加模型量化

### ISSUE THREAD

**Issue by Minami-su** [QwenLM/Qwen-VL#18]
如题

**Comment by Minami-su** [comment]
量化可以只针对llm

**Comment by simonJJJ** [comment]
We are working on it.

**Comment by Minami-su** [comment]
> We are working on it.

谢谢你们的工作

**Comment by 77h2l** [comment]
A10 22G , out of memory @simonJJJ

**Comment by ShuaiBai623** [comment]
The Int4 quantized model for Qwen-VL-Chat, [Qwen-VL-Chat-Int4](https://huggingface.co/Qwen/Qwen-VL-Chat-Int4), is available. about 12G cost
