### ISSUE TITLE
[BUG] <title> img_pos = torch.stack((bos_pos[0], bos_pos[1], eos_pos[1]), dim=1)

### ISSUE THREAD

**Issue by peace-zy** [QwenLM/Qwen-VL#182]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

8张A800运行finetune_ds.sh 报错
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/modeling_qwen.py", line 558, in forward
    img_pos = torch.stack((bos_pos[0], bos_pos[1], eos_pos[1]), dim=1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [0] at entry 2

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.11
- Transformers: 4.32.0
- PyTorch: 2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by MingDe-Li** [comment]
我也遇到这个问题，请问解决了吗
