### ISSUE TITLE
[BUG] Inconsistent prompt format

### ISSUE THREAD

**Issue by fffffarmer** [QwenLM/Qwen-VL#184]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

It seems like the behavior of `tokenizer.from_list_format` is different from the [format pattern described in README](https://github.com/QwenLM/Qwen-VL#data-preparation). Specifically, `tokenizer.from_list_format` produces `Picture id:<img>img_path</img>\n{your prompt}` whereas in README `Picture id: <img>img_path</img>\n{your prompt}` (w/ a whitespace after `Picture id:` is suggested.

### 期望行为 | Expected Behavior

Should it be consistent?

### 复现方法 | Steps To Reproduce

Running the following command produces `Picture 1:<img>assets/mm_tutorial/Rebecca_(1939_poster).jpeg</img>\nWhat is the name of the movie in the poster?`
```
query = tokenizer.from_list_format([
    {'image': 'assets/mm_tutorial/Rebecca_(1939_poster).jpeg'},
    {'text': 'What is the name of the movie in the poster?'},
])
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu
- Python:3.10.13
- Transformers:4.32.1
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by jinze1994** [comment]
Thank you for your contribution! There are certainly some inconsistencies here that can cause performance degradation. We have fixed this problem [HERE](https://huggingface.co/Qwen/Qwen-VL-Chat/commit/37124e214e313d50125bad97b23270b64acb012c).

**Comment by fffffarmer** [comment]
Thanks!
