### ISSUE TITLE
💡 [REQUEST] - 💡 [REQUEST] 您好，可以出一份使用自定义数据集进行Qwen-VL微调的教程或者说明文档么？ 

### ISSUE THREAD

**Issue by zfy1041264242** [QwenLM/Qwen-VL#19]
### 摘要 | Summary

希望增加一份使用自定义数据集的微调教程

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

希望增加一份使用自定义数据集的微调教程

### 未解决问题 | Unresolved questions

希望增加一份使用自定义数据集的微调教程

**Comment by ShuaiBai623** [comment]
感谢您的建议，我们会在之后的更新中增加这项功能，目前可以先参考这个[link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh)进行微调

**Comment by ShuaiBai623** [comment]
Thank you for your suggestion. We will definitely consider adding this feature in future updates. In the meantime, you can refer to this [link](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/qwen_vl/qlora_ddp/sft.sh) to finetune

**Comment by wjpstudy** [comment]
同求。目前用自己数据集在官方开放的Demo上效果没有很理想，因此很想尝试下在自定义数据集上微调之后的效果。迫切希望能够增加一份使用自定义数据集的微调教程，谢谢！

**Comment by dengfenglai321** [comment]
+1

**Comment by rover5056** [comment]
+1

**Comment by linxid** [comment]
> 
大概什么时间会开放微调代码和详细的setting呢

**Comment by zfy1041264242** [comment]
> 同求。目前用自己数据集在官方开放的Demo上效果没有很理想，因此很想尝试下在自定义数据集上微调之后的效果。迫切希望能够增加一份使用自定义数据集的微调教程，谢谢！

可以交流一下么，我这边也尝试进行了相关的微调工作，还是有一定效果的。

**Comment by aixiaodewugege** [comment]
> > 同求。目前用自己数据集在官方开放的Demo上效果没有很理想，因此很想尝试下在自定义数据集上微调之后的效果。迫切希望能够增加一份使用自定义数据集的微调教程，谢谢！
> 
> 可以交流一下么，我这边也尝试进行了相关的微调工作，还是有一定效果的。

可以 加微交流一下吗？同微调，wushuchenpp

**Comment by rover5056** [comment]
要不我们建个群一起交流下？ 拉了个Q群  865815609  
纯技术向 大家可以来分享交流

**Comment by aixiaodewugege** [comment]
> 要不我们建个群一起交流下？ 拉了个Q群 865815609 纯技术向 大家可以来分享交流 @zfy1041264242 @aixiaodewugege

ok 申请了

**Comment by jiumengs** [comment]
> 效果

申请了

**Comment by jiumengs** [comment]
> 要不我们建个群一起交流下？ 拉了个Q群 865815609 纯技术向 大家可以来分享交流 @zfy1041264242 @aixiaodewugege

申请了

**Comment by shams2023** [comment]
> [rover5056](/rover5056)

申请了 兄弟

**Comment by LLH-Harward** [comment]
> 要不我们建个群一起交流下？ 拉了个Q群 865815609 纯技术向 大家可以来分享交流 @zfy1041264242 @aixiaodewugege

申请了 兄弟
