### ISSUE TITLE
[BUG] <openai-api.py不支持图片识别>

### ISSUE THREAD

**Issue by vanche1212** [QwenLM/Qwen-VL#195]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-VL/assets/19466281/d36790c8-b3f7-45ad-ae00-0b1742f72cd2)

### 期望行为 | Expected Behavior

![image](https://github.com/QwenLM/Qwen-VL/assets/19466281/8ac5560d-05b4-4223-af3f-329818affe59)

### 复现方法 | Steps To Reproduce

以openai-api标准接口请求，发现content字段只能接受str

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by lhua1980** [comment]
臣附议

**Comment by ShuaiBai623** [comment]
目前可以通过<img>https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg</img>的方式加入图片，
```
query = tokenizer.from_list_format([
    {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'}, # Either a local path or an url
    {'text': '这是什么?'},
])
```
参照这个转化为文本

**Comment by MrRace** [comment]
希望可以跟OpenAI 的gpt-4-vision-preview对齐

**Comment by PPsteven** [comment]
@ShuaiBai623 没太看懂您这里的调用方式，tokenizer.from_list_format 这是哪里的方法，有具体的文档吗？
翻了相关issue，比如参考 https://help.aliyun.com/zh/dashscope/developer-reference/vl-plus-quick-start。
如果没有使用到dashscope的话，只是本地部署，通过http调用的话，好像这里的方式无法使用。您这里能否给出一个curl命令
像 gpt-4-vision-preview 一样的方式。

如果只是在content中加<img> 图片的话，
我的请求为
```bash
curl --location 'http://demo.com/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "Qwen-VL-Chat",
    "messages": [
      {
        "role": "user",
        "content": "描述如下图片: <img>https://i.ibb.co/0fWzSfS/xxxx.jpg</img>"
      }
    ],
    "max_tokens": 300
  }'
```

得到的结果如下
```json
{
    "model": "Qwen-VL-Chat",
    "object": "chat.completion",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "Received.",
                "function_call": null
            },
            "finish_reason": "stop"
        }
    ],
    "created": 1711355373
}
```

**Comment by PPsteven** [comment]
刚刚试了一下，发现 content 中的<img></img>如果包裹的是阿里云oss的地址的话，是可以正常输出的。可能qwen对于图片的地址还有一些限制。
