### ISSUE TITLE
[BUG] <词语”返回”触发图片理解任务BUG>

### ISSUE THREAD

**Issue by YumoeZhung** [QwenLM/Qwen-VL#197]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在[https://qianwen.aliyun.com/](https://qianwen.aliyun.com/)的图片理解模式下，开启新对话时，第一句直接输入”返回xxxxxxx“，将直接返回prompt的翻译：”Return xxxx“，如果更换”返回“为其他词，如”输出“，则不出现这个错误。
![微信图片编辑_20231211232359](https://github.com/QwenLM/Qwen-VL/assets/49787045/1a2940c3-ec8f-4bc0-9cca-d77073529d16)
![微信图片编辑_20231211223558](https://github.com/QwenLM/Qwen-VL/assets/49787045/37b0fc5f-8994-49cb-8f65-02293e443fc1)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
已更新，可以再试试
