### ISSUE TITLE
[BUG] <模型可支持的最大长度疑问>

### ISSUE THREAD

**Issue by hxtkyne** [QwenLM/Qwen-VL#198]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我看文档里面qwen-1.8b可支持的最大长度是32K，但是我看模型配置文件里面的·max_position_embeddings=8192·，所以模型可支持的最大长度是否是8192而不是32K？

### 期望行为 | Expected Behavior

qwen-1.8b可支持的最大长度是多少？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jinze1994** [comment]
语言模型可以到 https://github.com/QwenLM/Qwen/issues 下面提问哈。这里只讨论Qwen-VL模型。

**Comment by hxtkyne** [comment]
邮件已收到了哦亲，经常联系啊。好朋友走一生
