### ISSUE TITLE
[BUG] 不支持PNG图片框选元素，输出图片全黑

### ISSUE THREAD

**Issue by rujews** [QwenLM/Qwen-VL#20]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

上传一张PNG图片，然后让其框选图中的某个元素，输出的图片全部都是黑色的。

### 期望行为 | Expected Behavior

正常图片，正常框选。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

原因是把PLT库加载的png图片通道数据，也当成了RGB数据进行处理，因为PNG通道数据是0-1的float类似，强制转为int的RGB数据，就全部都是黑色的了。

**Comment by paulpaul91** [comment]
自己改下tokenization就可以

**Comment by rujews** [comment]
> 自己改下tokenization就可以

是的，我现在也是这么做的，期望官方修复下 @paulpaul91

**Comment by simonJJJ** [comment]
Hi @rujews, thanks for pointing this out, I have fixed the bug in the huggingface. Try it again~

**Comment by rujews** [comment]
OK了。我看代码，觉得没必要`np.asarray`一次，因为`Visualizer(image)`会会转，参考你上面网络图片的打开方式即可。 @simonJJJ

**Comment by simonJJJ** [comment]
@rujews Good catch! I will polish it.
