### ISSUE TITLE
finetune gt 准备

### ISSUE THREAD

**Issue by lh-seu** [QwenLM/Qwen-VL#200]
请问如果一张图片中有多个限速标志牌是，GT 提供box位置的时候应该以哪种形式提供
1.     <ref>限速标志牌</ref><box>(568, 132),(575, 144)</box><ref>限速标志牌</ref><box>(568, 115),(575, 126)</box><ref>限速标志牌</ref><box>(568, 150),(575, 162)</box><ref>限速标志牌</ref><box>(634, 118),(649, 145)</box><ref>限速标志牌</ref><box>(635, 174),(650, 201)</box>"
2.  <ref>限速标志牌</ref><box>(568, 132),(575, 144)</box><box>(568, 115),(575, 126)</box><box>(568, 150),(575, 162)</box><box>(634, 118),(649, 145)</box><box>(635, 174),(650, 201)</box>"
3.  <ref>四个限速标志牌</ref><box>(568, 132),(575, 144)</box><box>(568, 115),(575, 126)</box><box>(568, 150),(575, 162)</box><box>(634, 118),(649, 145)</box><box>(635, 174),(650, 201)</box>"
如果以上三种形式都不对，能请教下正确的形式吗

**Comment by lh-seu** [comment]
感谢感谢

**Comment by sunjunlishi** [comment]
@ShuaiBai623 身份证关键信息提取怎么设计

**Comment by sunjunlishi** [comment]
@ShuaiBai623 
@ShuaiBai623 身份证关键信息提取怎么设计
这样吗
<ref>姓名</ref><box>(568, 132),(575, 144)</box>
<ref>民族</ref><box>(568, 115),(575, 126)</box>
<ref>性别</ref><box>(568, 150),(575, 162)</box>
<ref>地址</ref><box>(634, 118),(649, 145)</box>
<ref>身份证号</ref><box>(635, 174),(650, 201)</box>

**Comment by sunjunlishi** [comment]
@ShuaiBai623 有没有仅仅处理位置和文本信息的大模型，比如处理 pdf格式提取出来的文本信息的大模型

**Comment by sunjunlishi** [comment]
@ShuaiBai623 已解决。
![微信图片_20240410192009](https://github.com/QwenLM/Qwen-VL/assets/11845664/14ff6dfd-78ff-42b6-8f28-9af472699b82)
多个中间加逗号
