### ISSUE TITLE
[BUG] 模型加载出错

### ISSUE THREAD

**Issue by Limingxing00** [QwenLM/Qwen-VL#208]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在visual.py中新增了一些模块，训练过程中是正常训练的，但似乎这部分权重没有被正常保存，所以在推理的时候加载报错：
<img width="1894" alt="image" src="https://github.com/QwenLM/Qwen-VL/assets/23522700/cc28495a-0fe2-47c0-a249-8f32558a99c6">

请问我应该怎么做？

### 运行环境 | Environment

```Markdown
与推荐相同
```

**Comment by ShuaiBai623** [comment]
修改的话，需要从指定路径load，是不是模型定义的路径不对导致参数不匹配的

**Comment by Limingxing00** [comment]
> 修改的话，需要从指定路径load，是不是模型定义的路径不对导致参数不匹配的

感谢您及时的回复，我正确加载了**保存模型的路径**，是因为我采用了AutoPeftModelForCausalLM的方式加载模型吗？我是一名hugging face社区的新手，如果我在vit的visual.py文件新增了训练模块，我应该如何加载模型？

```python
    model = AutoPeftModelForCausalLM.from_pretrained(
        args.checkpoint, # path to the output directory
        device_map="cuda",
        trust_remote_code=True,
    ).eval()
```

**Comment by Limingxing00** [comment]
是不是使用finetune_lora_single_gpu.sh的时候你们只保存了lora相关的参数，我使用的是finetune_lora_single_gpu.sh。我应该如何修改

**Comment by Limingxing00** [comment]
是我的格式问题。。谢谢已经解决

**Comment by ParanoidW** [comment]
> 是我的格式问题。。谢谢已经解决
@Limingxing00 你好，我也遇到了同样的问题。请问你最后是怎么解决的？

**Comment by shadowboxx** [comment]
> > 是我的格式问题。。谢谢已经解决
> 
> @Limingxing00 你好，我也遇到了同样的问题。请问你最后是怎么解决的？

同问
