### ISSUE TITLE
qwen vl plus 是否已开放模型文件？

### ISSUE THREAD

**Issue by blue-vision0** [QwenLM/Qwen-VL#213]
请问目前qwen vl plus 是否已经开放模型文件，允许私有化部署？目前model scope 和huggingface上的qwen vl 库中的模型文件就是qwen vl plus 的权重吗？

**Comment by jinze1994** [comment]
qwen-vl-plus没有开放模型文件。
modelscope和huggingface上的qwenvl库是8月底开源的qwen-vl-7B模型，不是qwen-vl-plus的权重。
qwen-vl-plus目前可以通过[网页](https://tongyi.aliyun.com/qianwen)和[API](https://help.aliyun.com/zh/dashscope/developer-reference/vl-plus-quick-start)访问。

**Comment by xiao2mo** [comment]
> qwen-vl-plus没有开放模型文件。
> modelscope和huggingface上的qwenvl库是8月底开源的qwen-vl-7B模型，不是qwen-vl-plus的权重。
> qwen-vl-plus目前可以通过[网页](https://tongyi.aliyun.com/qianwen)和[API](https://help.aliyun.com/zh/dashscope/developer-reference/vl-plus-quick-start)访问。

when to release? b.t.w
