### ISSUE TITLE
[Implementation of increasing image resolution from 224 to 448]

### ISSUE THREAD

**Issue by g-h-chen** [QwenLM/Qwen-VL#215]
HI folks, thanks for your nice work!!

Just a quick question: How did you increase the image resolution from 224 to 448? Or more essentially, how to deal with the increased sequence length from 576 to 1024 for image encoder? There should be some problem in the position encoding here. 

Thanks in advance!

**Comment by vealocia** [comment]
Please refer to [here](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/6665c780ade5ff3f08853b4262dcb9c8f9598d42/visual.py#L367). Our position embedding is always stored in 256 length and we adaptively interpolate it to larger size during [training](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/6665c780ade5ff3f08853b4262dcb9c8f9598d42/visual.py#L402).

**Comment by g-h-chen** [comment]
Crystal! Thanks!
