### ISSUE TITLE
如何从Q-LoRA微调的checkpoint中加载模型继续训练？

### ISSUE THREAD

**Issue by zhaohm14** [QwenLM/Qwen-VL#225]
我使用qlora微调了模型并保存了checkpoint，现在我希望从checkpoint接着训练几个epoch。
请问将 finetune.py 的 train() 中的 model 直接改为 AutoPeftModelForCausalLM.from_pretrained 是否可以断点续训？其他训练参数会正确加载吗？
谢谢

**Comment by ks-wfc** [comment]
同问

**Comment by ks-wfc** [comment]
https://stackoverflow.com/questions/72672281/does-huggingfaces-resume-from-checkpoint-work
直接设置这个我感觉就行
trainer.train(resume_from_checkpoint=True)

**Comment by zhaohm14** [comment]
> https://stackoverflow.com/questions/72672281/does-huggingfaces-resume-from-checkpoint-work 直接设置这个我感觉就行 trainer.train(resume_from_checkpoint=True)

尝试了，可行，多谢！
