### ISSUE TITLE
和qwen-72B效果比较

### ISSUE THREAD

**Issue by jun0wanan** [QwenLM/Qwen-VL#226]
您好，感谢您们优秀的工作：

我最近在测试您们模型的图文混合理解的时候，发现好像效果不如直接将文本给qwen-72B模型完成我的任务完成的那么好，因为可能我给的图文，图只是起辅助作用，我很好奇所以现在的qwen-vl-plus在文本理解指令方面，是不是比qwen-72B差很多呀？我给它很多复杂的指令好像执行得一般？不知道是不是我测试不对的问题。
          希望得到您的回复！

**Comment by whysirier** [comment]
肯定的啊，qwen-vl是基于qwen-7b改的好像

**Comment by jun0wanan** [comment]
> 肯定的啊，qwen-vl是基于qwen-7b改的好像

好吧hhh，感觉没72B强欸，如果能基于72B改就好了

**Comment by sunjunlishi** [comment]
基于14B量化的也可以。网络结构很重要。已经开源的思路已经不错。自动生成数据吧。
