### ISSUE TITLE
[BUG] <我想将长度不够的句子进行token填充，但好像出现错误 `add_special_tokens`的使用>

### ISSUE THREAD

**Issue by nuocheng** [QwenLM/Qwen-VL#228]
### 复现方法 | Steps To Reproduce

下面是我的代码部分：
~~~python
tokenizer=AutoTokenizer.from_pretrained("Qwen/Qwen-7B", use_fast=False,trust_remote_code=True)
if tokenizer.pad_token is None:
	 tokenizer.add_special_tokens({"pad_token":'[PAD]'})
~~~

### 出现的问题：

`File "Qwen-7B/tokenization_qwen.py", line 165, in _add_tokens  raise ValueError("Adding unknown special tokens is not supported")  ValueError: Adding unknown special tokens is not supported`

### debug后发现tokenizer将 special_tokens加入其中，但是程序退出，无法继续
下面是add_special_tokens的结果
`QWenTokenizer(name_or_path='Qwen/Qwen-7B', vocab_size=151851, model_max_length=32768, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'pad_token': '[PAD]'}, clean_up_tokenization_spaces=True)`

### 尝试解决出现的其他问题：
我将`Qwen-7B/tokenization_qwen.py  line 165` 相关报错注释掉之后，使用`[PAD]`进行padding，但是发现使用token进行分词的时候出现`[PAD]`没有找到id的问题。

Qwen模型是使用的什么特殊字符进行的填充的呢，以及上面的问题如何解决

**Comment by vealocia** [comment]
你好，我们在评测中也使用了对输入序列的pad，具体代码可见[这里](https://github.com/QwenLM/Qwen-VL/blob/5ffae05ab30fa45f6b9c09541feadc4821e8e6ba/eval_mm/evaluate_caption.py#L119)。我们在评测中没有遇到上述问题。

**Comment by nuocheng** [comment]
> 你好，我们在评测中也使用了对输入序列的pad，具体代码可见[这里](https://github.com/QwenLM/Qwen-VL/blob/5ffae05ab30fa45f6b9c09541feadc4821e8e6ba/eval_mm/evaluate_caption.py#L119)。我们在评测中没有遇到上述问题。

好的，感谢回复，我发现在进行在配置padding使用的特殊字符，使用的是
https://github.com/QwenLM/Qwen-VL/blob/5ffae05ab30fa45f6b9c09541feadc4821e8e6ba/eval_mm/evaluate_caption.py#L122

也就是pad和eod使用的是同一个特殊字符，是否需要对这两个特殊字符进行区分（不同特殊字符代表不同含义，不存在不同含义使用相同的特殊字符）。
