### ISSUE TITLE
💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by paulpaul91** [QwenLM/Qwen-VL#23]
### 起始日期 | Start Date

08/28/2023

### 相关Issues | Reference Issues

有两个问题想请教下：
1. 在pretrain和multi-task pretrain分别使用了多少资源，预计需要多长时间
2. 对于纯文效果，有多少损伤，有没有可比较结果

### 摘要 | Summary

*

### 基本示例 | Basic Example

*

### 缺陷 | Drawbacks

*

**Comment by logicwong** [comment]
你好，感谢你对我们工作的关注

1. 有关训练资源的细节暂时还不会公布，后续如果有更新会放到arxiv论文上；
2. 我们在MMLU和CMMLU上评测了Qwen-VL的效果，虽然相较于纯文本Qwen-7B有些下降，但它依然在这两个数据集上取得了比较领先的结果，希望这份结果对你有帮助。

| Model        |   MMLU   |  CMMLU  |
| :------------- | :--------: | :--------: |
| LLaMA-7B     |   35.1   |    -    |  
| Baichuan-7B  |   42.3   |   44.4   |
| ChatGLM2-6B  |   47.9   |   48.8   |
| Qwen-7B  | **56.7** |  **58.8**  | 
| Qwen-VL  |  50.7 | 49.5 |
