### ISSUE TITLE
❓[Question] The processing details of grounding dataset GRIT

### ISSUE THREAD

**Issue by sennnnn** [QwenLM/Qwen-VL#24]
The origin paper describes the GRIT processing details: "We use the greedy algorithm to clean the caption to make sure each image contains the most box labels with no recursive box labels." 

What does this exactly mean? Can you provide some examples to explain this operation? 

Thanks.

**Comment by vealocia** [comment]
Hi @sennnnn!
In short, GRIT dataset annotates many bboxes for a given image-text pair, each bbox is associated with a chunk of text, and there maybe some overlaps on corresponding text-chunks between different bboxes. For instance, an image may be annotated as:
```
caption: a dog in a field of flowers
a dog: [290,371,605,750]
a field: [0,264,919,921]
a dog in a field of flowers: [290,371,605,750]
```
Obviously, `a dog` and `a field` are overlapped to (actually included in) `a dog in a field of flowers`.
Under such circumstance, we greedily sample data with the most possible non-overlapped bboxes. That's to say, for the above exampler, we use the following annotation
```
caption: a dog in a field of flowers
a dog: [290,371,605,750]
a field: [0,264,919,921]
```
and drop the other bboxes.
Hope this answer can help u and we will add more details to our paper in next revision.

**Comment by sennnnn** [comment]
Really thanks to your solid response 🙏🙏

**Comment by sennnnn** [comment]
Moreover, is there any extra processing details and advice about noun chunks with multiple boxes?

**Comment by vealocia** [comment]
We just keep all boxes.

**Comment by sennnnn** [comment]
Ok, thanks 🚀
