### ISSUE TITLE
[BUG] 使用A100运行时出现SegmentFault(Core Dump)

### ISSUE THREAD

**Issue by Carol-gutianle** [QwenLM/Qwen-VL#256]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

模型成功被load，但是当进行model.chat推理时出现SegmentFault(Core Dump)报错

### 运行环境 | Environment

```Markdown
- OS: CentOS 7
- Python:3.10
- Transformers:4.36.2
- PyTorch:2.1.2+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jinze1994** [comment]
我们这边在a100上的实验并未出现这个问题，需要您提供更多信息。或者可以通过print判定出错位置。

**Comment by WangChen100** [comment]
@Carol-gutianle 你好，我也遇到了一样的问题，请问你是怎么解决的？没有报错，就跳出一行Segmentation fault
