### ISSUE TITLE
請問如何對使用qlora finetune後的model進行infer?

### ISSUE THREAD

**Issue by charlescwwang** [QwenLM/Qwen-VL#258]
您好，透過finetune文件說明，自己簡單建構了data數據後，用`sh finetune/finetune_lora_single_gpu.sh`進行finetune。
但是不清楚後續該如何infer，自行嘗試建構以下程式碼執行，會出現錯誤 ValueError: Target module QuantLinear() is not supported.
請問是我少了什麼步驟嗎？
謝謝

```python 
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch
torch.manual_seed(1234)
from peft import AutoPeftModelForCausalLM

image_path = 'path_to_14753.jpg'
path_to_adapter = '/home/localroot/Qwen-VL/output_qwen'
peft_model_id = "Qwen/Qwen-VL-Chat-Int4"

tokenizer = AutoTokenizer.from_pretrained(peft_model_id,resume_download=True, trust_remote_code=True)

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()

history = None
response, history = model.chat(tokenizer, query=f'<img>{image_path}</img>這是什麼建築物?', history=None)
print(response)
response, history = model.chat(tokenizer, '框出建築物', history=history)
print(response)

image = tokenizer.draw_bbox_on_latest_picture(response, history)
if image:
  image.save('output_chat.jpg')
else:
  print("no box")
```

錯誤訊息
```
(Qwen-VL) localroot@ubuntu22:~/Qwen-VL$ python model_q_infer.py 
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.77it/s]
Traceback (most recent call last):
  File "/home/localroot/Qwen-VL/model_q_infer.py", line 22, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/auto.py", line 103, in from_pretrained
    return cls._target_peft_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 351, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 1043, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 125, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 90, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 247, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 202, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 355, in _create_new_module
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
```

**Comment by charlescwwang** [comment]
透過這篇，看來是套件版本問題，可以成功infer，謝謝。
https://github.com/QwenLM/Qwen/issues/610

**Comment by xiayq1** [comment]
> 您好，透過finetune文件說明，自己簡單建構了data數據後，用`sh finetune/finetune_lora_single_gpu.sh`進行finetune。 但是不清楚後續該如何infer，自行嘗試建構以下程式碼執行，會出現錯誤 ValueError: Target module QuantLinear() is not supported. 請問是我少了什麼步驟嗎？ 謝謝
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from transformers.generation import GenerationConfig
> import torch
> torch.manual_seed(1234)
> from peft import AutoPeftModelForCausalLM
> 
> image_path = 'path_to_14753.jpg'
> path_to_adapter = '/home/localroot/Qwen-VL/output_qwen'
> peft_model_id = "Qwen/Qwen-VL-Chat-Int4"
> 
> tokenizer = AutoTokenizer.from_pretrained(peft_model_id,resume_download=True, trust_remote_code=True)
> 
> model = AutoPeftModelForCausalLM.from_pretrained(
>     path_to_adapter, # path to the output directory
>     device_map="auto",
>     trust_remote_code=True
> ).eval()
> 
> history = None
> response, history = model.chat(tokenizer, query=f'<img>{image_path}</img>這是什麼建築物?', history=None)
> print(response)
> response, history = model.chat(tokenizer, '框出建築物', history=history)
> print(response)
> 
> image = tokenizer.draw_bbox_on_latest_picture(response, history)
> if image:
>   image.save('output_chat.jpg')
> else:
>   print("no box")
> ```
> 
> 錯誤訊息
> 
> ```
> (Qwen-VL) localroot@ubuntu22:~/Qwen-VL$ python model_q_infer.py 
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.77it/s]
> Traceback (most recent call last):
>   File "/home/localroot/Qwen-VL/model_q_infer.py", line 22, in <module>
>     model = AutoPeftModelForCausalLM.from_pretrained(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/auto.py", line 103, in from_pretrained
>     return cls._target_peft_class.from_pretrained(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 351, in from_pretrained
>     model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 1043, in __init__
>     super().__init__(model, peft_config, adapter_name)
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/peft_model.py", line 125, in __init__
>     self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 111, in __init__
>     super().__init__(model, config, adapter_name)
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 90, in __init__
>     self.inject_adapter(self.model, adapter_name)
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 247, in inject_adapter
>     self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 202, in _create_and_replace
>     new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/localroot/anaconda3/envs/Qwen-VL/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 355, in _create_new_module
>     raise ValueError(
> ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
> ```



请问一个问题，你这个是使用qlora训练的vl吗？
我看你显示的是lora啊：sh finetune/finetune_lora_single_gpu.sh。
我现在使用qlora，会报错说不支持。会显示：support for vision, speech and multimodel will come later

**Comment by charlescwwang** [comment]
是用qlora沒錯，上面筆誤，已修正為 finetune/finetune_qlora_single_gpu.sh，謝謝

**Comment by charlescwwang** [comment]
不確定您遇到的問題，但我碰到的錯誤大多是套件版本問題
所以最終我是參照這條回覆修改 https://github.com/QwenLM/Qwen/issues/610#issuecomment-1805150953
看錯誤訊息猜測，可能model設定成其他版本，所以他說目前不支援

**Comment by xiayq1** [comment]
> 不確定您遇到的問題，但我碰到的錯誤大多是套件版本問題 所以最終我是參照這條回覆修改 [QwenLM/Qwen#610 (comment)](https://github.com/QwenLM/Qwen/issues/610#issuecomment-1805150953) 看錯誤訊息猜測，可能model設定成其他版本，所以他說目前不支援

感谢
