### ISSUE TITLE
[BUG] <title>When loading the lora adapter weight: ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by 1024-xx** [QwenLM/Qwen-VL#266]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:Linux
- Python:3.8.18
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

### 备注 | Anything else?

When I run the given code:
from peft import AutoPeftModelForCausalLM
model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()

Traceback (most recent call last):
  File "cs.py", line 9, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/datas/xupengyuan/.conda/envs/qwen/lib/python3.8/site-packages/peft/auto.py", line 124, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
  File "/datas/xupengyuan/.conda/envs/qwen/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

**Comment by 1024-xx** [comment]
for
File "/datas/xupengyuan/.conda/envs/qwen/lib/python3.8/site-packages/peft/auto.py", line 124, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
I made such changes, and now there will be no errors. But I don't know if it's the right thing to do：
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)->tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path, trust_remote_code=True)

**Comment by cq1316** [comment]
这个问题你解决了吗？我也碰到了

**Comment by ypw-lbj** [comment]
同问！ 解决了一天

**Comment by cq1316** [comment]
> 同问！ 解决了一天

我试下来是这样的情况：如果用原模型，需要先实例化tokenizer，再实例化模型。如果是训练的模型，需要先实例化模型，再实例化tokenizer。你可以试试

**Comment by ypw-lbj** [comment]
> > 同问！ 解决了一天
> 
> 我试下来是这样的情况：如果用原模型，需要先实例化tokenizer，再实例化模型。如果是训练的模型，需要先实例化模型，再实例化tokenizer。你可以试试

@cq1316 您是指:
先执行 tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat-Int4", trust_remote_code=True)
再执行 model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat-Int4", device_map=True)

是这个意思吗？
我已经试过了，不太行

**Comment by yangyijune** [comment]
My solution is to replace the autotokenizer as QWenTokenizer directly

```from tokenization_qwen import QWenTokenizer
from transformers.generation import GenerationConfig
import torch
torch.manual_seed(77)

# Note: The default behavior now has injection attack prevention off.
tokenizer = QWenTokenizer.from_pretrained("/bian_data/qwen-VL/Qwen-VL-Chat", trust_remote_code=False)```

**Comment by hl-gl** [comment]
> 我的解决方案是直接将 autotokenizer 替换为 QWenTokenizer
> 
> ```
> from transformers.generation import GenerationConfig
> import torch
> torch.manual_seed(77)
> 
> # Note: The default behavior now has injection attack prevention off.
> tokenizer = QWenTokenizer.from_pretrained("/bian_data/qwen-VL/Qwen-VL-Chat", trust_remote_code=False)```
> ```

如果按照上面替换，第二条加载模型的命令还是会走老路，请问如何解决呢？谢谢：
model = AutoModelForCausalLM.from_pretrained("checkpoint-1800-merged", device_map="cuda", trust_remote_code=False).
