### ISSUE TITLE
[BUG] <title>lora训练后，模型加载报错Tokenizer class QWenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by cq1316** [QwenLM/Qwen-VL#269]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-VL/assets/9404745/180131aa-2c90-4ad9-9013-5eada54adefc)
用官方文档的lora进行训练，训练完成后得到输出文件夹
![image](https://github.com/QwenLM/Qwen-VL/assets/9404745/ca2aa6aa-e308-40ef-b40e-a3649cc01b86)
用官方文档提供的模型加载方式
![image](https://github.com/QwenLM/Qwen-VL/assets/9404745/e99539c9-3b45-4e48-a12e-71ad84afe5f5)
报错
![image](https://github.com/QwenLM/Qwen-VL/assets/9404745/28afa12b-68fc-422b-85dc-854de80d9d78)

### 期望行为 | Expected Behavior

按官方文档走应该不会错才对吧

### 运行环境 | Environment

```Markdown
- OS:linux
- Python:3.10
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by zzzcccxx** [comment]
一样的报错

**Comment by cq1316** [comment]
> 一样的报错

我自己解决了，我的原因是peft最新版是0.8，在导入本地模型的时候，导入tokenizer的函数里没有trust_remote_code=true的参数。我把peft降到0.7版本，然后重新训练模型，就可以跑起来了。

一定要重新训练模型，因为之前到模型是peft 0.8训练的，用0.7测试会报错

**Comment by zzzcccxx** [comment]
> > 一样的报错
> 
> 我自己解决了，我的原因是peft最新版是0.8，在导入本地模型的时候，导入tokenizer的函数里没有trust_remote_code=true的参数。我把peft降到0.7版本，然后重新训练模型，就可以跑起来了。
> 
> 一定要重新训练模型，因为之前到模型是peft 0.8训练的，用0.7测试会报错

非常感谢，已跑通

**Comment by cyb1219257828** [comment]
> > 一样的报错
> 
> 我自己解决了，我的原因是peft最新版是0.8，在导入本地模型的时候，导入tokenizer的函数里没有trust_remote_code=true的参数。我把peft降到0.7版本，然后重新训练模型，就可以跑起来了。
> 
> 一定要重新训练模型，因为之前到模型是peft 0.8训练的，用0.7测试会报错

非常感谢您，同样的报错，已跑通
