### ISSUE TITLE
Is the LLM part the same as Qwen7B-Chat?

### ISSUE THREAD

**Issue by abussseee** [QwenLM/Qwen-VL#3]
Is the LLM part the same as Qwen7B-Chat?

**Comment by tfka** [comment]
> The LLM part was initialized from Qwen7B (not Chat version). And we fine-tuned it in further training.

In the VL model, both the base version and the chat version use lightweight tuning methods like LORA or full-parameter fine-tuning on LLM?

**Comment by simonJJJ** [comment]
@tfka, we fully fine-tuned LLM.
