### ISSUE TITLE
[BUG] Failed to use inputs_embeds instead of inputs_ids in generate function.

### ISSUE THREAD

**Issue by yyk-wew** [QwenLM/Qwen-VL#30]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

In Qwen-VL-Chat, the model takes an url or local path as input to load images. I tried to load images with a pre-defined dataset and build `inputs_embeds` out of the forward function.

When I tried to pass `inputs_embeds` into generate function, the following line (the first line in the forward function of `QwenModel`) raise an error:
```python
if past_key_values is None and torch.any(input_ids == self.config.visual['image_start_id']):
```
The `input_ids` here is `None` and the result is `False` (a bool). `torch.any` needs a tensor as input rather than a bool and the error is raised.

I think a quick check on whether the `input_ids` is None or a tensor could fix it.
```python
if past_key_values is None and input_ids is not None and torch.any(input_ids == self.config.visual['image_start_id']):
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
Thank you for your reminder. We will fix this bug.

**Comment by Practicing7** [comment]
Could I ask how you create input_embeds outside of the generate function. Is it simply using tokenizer.encode and wte these  two function?

**Comment by MM-WW55** [comment]
I still have this problem, the files on huggingface are not getting updated
