### ISSUE TITLE
Qwen-vl-plus和Qwen-vl-max有对chat进行优化吗?

### ISSUE THREAD

**Issue by yilun-hua** [QwenLM/Qwen-VL#321]
### 摘要 | Summary

Qwen-vl-plus和Qwen-vl-max有像qwen-vl-chat一样对多图场景和对轮对话优化吗? 

### 基本示例 | Basic Example

API documentation和repo里面只提到了qwen-vl-chat 支持灵活的交互方式，包括多图、多轮问答、创作等能力的模型, 没有针对vl-plus和max的信息

### 缺陷 | Drawbacks

请见上文

**Comment by jinze1994** [comment]
有的，qwen-vl-plus和qwen-vl-max都是chat模型，不是pretrain模型。是qwen-vl-chat(开源7b)的升级版
