### ISSUE TITLE
[问题] 咨询问题，在2张4090的显卡上能不能微调训练？

### ISSUE THREAD

**Issue by wangqinghuan** [QwenLM/Qwen-VL#357]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by fang-d** [comment]
可以。我在单张RTX 4090上完成了微调训练。

**Comment by ezyzzy** [comment]
> 可以。我在单张RTX 4090上完成了微调训练。

啥配置啊，lora还是q lora呀
