### ISSUE TITLE
💡 [REQUEST] - Replicate API

### ISSUE THREAD

**Issue by kenhuang1964** [QwenLM/Qwen-VL#36]
### 摘要 | Summary

It would be awesome if you guys could upload the model to replicate.com so it is more accessible in applications. 

### 基本示例 | Basic Example

This is a popular website for model deployment. It would be awesome if you guys could upload it here so we can use the model API. https://replicate.com/

### 缺陷 | Drawbacks

There are no drawbacks.

**Comment by simonJJJ** [comment]
Hi @kenhuang1964, thanks for the suggestion, we will work on it soon.
