### ISSUE TITLE
使用3000份数据全量参数微调10个epoch后依然有很大的幻觉，并且一个回答里面会重复生成

### ISSUE THREAD

**Issue by yuemengrui** [QwenLM/Qwen-VL#365]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by lyc728** [comment]
先训练100epoch试下

**Comment by whycantfindaname** [comment]
想问问全量微调需要的显存在多少呀，我们用h20 batchsize只能开2

**Comment by yuemengrui** [comment]
> 想问问全量微调需要的显存在多少呀，我们用h20 batchsize只能开2

我是八卡A100 80G的服务器，显存够用

**Comment by whycantfindaname** [comment]
感谢!还想问问您的model max length设置是多少呢？对应batch size能开到多大啊
