### ISSUE TITLE
[BUG] <title>AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'

### ISSUE THREAD

**Issue by sulaiman1988** [QwenLM/Qwen-VL#387]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

this error happened when running inference after finetuning the model on the custom dataset using finetune_qlora_ds.sh 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by fang-d** [comment]
@sulaiman1988 I also encountered this problem during deploying the fine-tuned model. Could you please share your solution to this problem or the correct way to deploy the fine-tuned model? Thank you!

**Comment by GXKIM** [comment]
The same error
