### ISSUE TITLE
💡 [REQUEST] - 能调用backbone抽feature吗？

### ISSUE THREAD

**Issue by jyC23333** [QwenLM/Qwen-VL#39]
### 摘要 | Summary

这个模型能用到图文检索中吗，类似clip那种？
怎样调用backbone抽feature，有代码参考吗？

### 基本示例 | Basic Example

---

### 缺陷 | Drawbacks

---

**Comment by simonJJJ** [comment]
Hi, @jyC23333,
1. No, without fine-tuning, you can not use the model directly on Image-Text retrieval.
2. Our ViT model is the same as openclip except we drop the class token. You can directly load the model. The details of the model are on [hugginface](https://huggingface.co/Qwen/Qwen-VL/blob/main/modeling_qwen.py).

**Comment by jyC23333** [comment]
@simonJJJ Hi, Thanks a lot.
1. As mentioned, I can't regard the whole model as  ```image encoder + text encoder```, is it?
2. does it make any sense to extract image feature using ViT and to extract text feature using LLM backbone?
Because after alignment between the two kinds of features, I think the model has learned the relationship of the two domain.
