### ISSUE TITLE
Pretrain数据格式

### ISSUE THREAD

**Issue by jweihe** [QwenLM/Qwen-VL#414]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

您好，请问Pretrain数据格式大概是什么样的呢，这里可以提供一些吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by CarlHuangNuc** [comment]
@jweihe  Hi  请教一下，怎么拿到Pretrain 后的模型进行SFT ??
