### ISSUE TITLE
Normalization Range

### ISSUE THREAD

**Issue by jiafei1224** [QwenLM/Qwen-VL#45]
Hi, 
Can i check how do i get the normalisation range so that i can re-project the draw box coordinates myself on the same image? Or is there anyway to access the bbox_drawing function?

**Comment by vealocia** [comment]
Hi, @jiafei1224~ Thanks for your interest in our work.
You can find the code of drawing box at [here](https://huggingface.co/Qwen/Qwen-VL/blob/db0c725e4e808218c69cc194f660cb5b6da7f04c/tokenization_qwen.py#L457)
