### ISSUE TITLE
[BUG] <title> 计算ANLS指标时执行了infographicsvqa_eval.py，然而没有找到这个文件。

### ISSUE THREAD

**Issue by zhengx18** [QwenLM/Qwen-VL#46]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

evaluate_vqa.py 在docvqa 数据集上计算anls指标时，执行了python infographicsvqa_eval.py文件，然而没有找到这个代码。

**Comment by vealocia** [comment]
Hi @zhengx18! Thanks for your interest in our work.
This python script is already put [here](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/infographicsvqa_eval.py). Please make sure you execute the evaluation command under the ```eval_mm``` directory.
