### ISSUE TITLE
[BUG]  通义千问2-VL-MAX 输出内容死循环

### ISSUE THREAD

**Issue by OptimisticGeek** [QwenLM/Qwen-VL#482]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/user-attachments/assets/8caafd5a-e40f-43d9-9af3-4ec6f932bc6e)

### 期望行为 | Expected Behavior

分析文中人物详细特点

### 复现方法 | Steps To Reproduce

[error.txt](https://github.com/user-attachments/files/17464531/error.txt)
该文件是元空间的html代码，可以将文件后缀改为html更利于查看。

### 运行环境 | Environment

```Markdown
创空间：https://www.modelscope.cn/studios/Qwen/Qwen2-VL
```

**Comment by OptimisticGeek** [comment]
额外一种情况，同样的案例，但最后我要求通义千问生成人物关系图时，也出现了死循环，但是日志忘记保留了，时间发生于：10月22日 00:38~00:45之间。
使用Mermaid绘制关系图，"A->B,B->C...........BA->BB"这样的结果

**Comment by QixingJiang** [comment]
这是一个通病，qwen2-vl的各个模型都有，小模型这个问题更多，你可以修改generation_config中的参数frequency_penalty(设置为[-2.0, 2.0]，正数代表惩罚重复输出)试试。

**Comment by OptimisticGeek** [comment]
谢谢啊，不太清楚这个，小萌新一枚。
