### ISSUE TITLE
💡 [REQUEST] - Request for complete evaluation data

### ISSUE THREAD

**Issue by Artanic30** [QwenLM/Qwen-VL#49]
### 起始日期 | Start Date

9/1/23

### 摘要 | Summary

Hello, I appreciate your prompt response in providing evaluation data. Upon reviewing the information, I've noticed that certain datasets, such as GQA and docvqa, have not been released yet. I'm curious if there is a planned schedule for the release of the remaining evaluation data. Thank you.

### 基本示例 | Basic Example

data annotation files in eval_mm/EVALUATION.md

### 缺陷 | Drawbacks

Some evaluation data is missing.

**Comment by vealocia** [comment]
Hi @Artanic30, more evaluation files and scripts are provided now.
