### ISSUE TITLE
[BUG] <title>Qwen/Qwen-VL-Chat-Int4，加载时没有任何反应，就死在那里

### ISSUE THREAD

**Issue by tutu329** [QwenLM/Qwen-VL#50]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
    ).eval()
这段代码运行毫无反应，而checkpoint_path反复检查过多次，没有问题。

### 期望行为 | Expected Behavior

加载成功

### 运行环境 | Environment

```Markdown
- OS:win11
- Python:3.10.11
- Transformers:
- PyTorch:2.01
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by vealocia** [comment]
Hi, @tutu329. That's really weird. I suggest you move to our wechat or discord group for more convinient communication.

**Comment by jinze1994** [comment]
Try this [Colab](https://colab.research.google.com/github/camenduru/Qwen-VL-Chat-colab/blob/main/Qwen_VL_Chat_colab.ipynb) contributed by [camenduru](https://github.com/camenduru/Qwen-VL-Chat-colab) as a tutorial of the Qwen/Qwen-VL-Chat-Int4 demo.
