### ISSUE TITLE
视频

### ISSUE THREAD

**Issue by wjfwjfwjf** [QwenLM/Qwen-VL#57]
请问模型支持视频吗？为什么SEED-Bench上有视频的评分？

**Comment by ShuaiBai623** [comment]
we directly and uniformly sample 4 frames of the video as input in SEED-Bench

**Comment by jinze1994** [comment]
Qwen-VL 没有使用视频数据训练过，但它可以zero-shot被用于视频理解，即直接在视频中均匀采样四帧，以多图在上下文中并列输入模型，具体处理细节可以参考[这里](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/seed_bench/EVAL_SEED.md)。我们据此在SEED-Bench上对模型的视频能力进行了评测，并且取得了不错的结果。

**Comment by CrazyBrick** [comment]
> Qwen-VL 没有使用视频数据训练过，但它可以zero-shot被用于视频理解，即直接在视频中均匀采样四帧，以多图在上下文中并列输入模型，具体处理细节可以参考[这里](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/seed_bench/EVAL_SEED.md)。我们据此在SEED-Bench上对模型的视频能力进行了评测，并且取得了不错的结果。

我看到了huggingface上面的demo
`tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

# use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
# use fp16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
# use cpu only
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cpu", trust_remote_code=True).eval()
# use cuda device
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cuda", trust_remote_code=True).eval()

# Specify hyperparameters for generation (No need to do this if you are using transformers>=4.32.0)
# model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

# 1st dialogue turn
query = tokenizer.from_list_format([
    {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'},
    {'text': '这是什么'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)
# 图中是一名年轻女子在沙滩上和她的狗玩耍，狗的品种可能是拉布拉多。她们坐在沙滩上，狗的前腿抬起来，似乎在和人类击掌。两人之间充满了信任和爱。
`
这边的query是单一图片的方式，请问你们是怎么让它以多图并列输入并缝合到上下文中的呢？我不太理解您给出的例子：
`{
  "question_id": "v0",
  "prompt": "<img>video_imgs_4/v0_0.jpg</img>\n<img>video_imgs_4/v0_1.jpg</img>\n<img>video_imgs_4/v0_2.jpg</img>\n<img>video_imgs_4/v0_3.jpg</img>\nQuestion: Can you identify the action taking place in the video?\nOptions: A. pretending to take something out of something\nB. pretending to take something from somewhere\nC. feigning to insert something into something\nD. simulating putting something onto something\nAnswer:"
}`

**Comment by CrazyBrick** [comment]
> Qwen-VL 没有使用视频数据训练过，但它可以zero-shot被用于视频理解，即直接在视频中均匀采样四帧，以多图在上下文中并列输入模型，具体处理细节可以参考[这里](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/seed_bench/EVAL_SEED.md)。我们据此在SEED-Bench上对模型的视频能力进行了评测，并且取得了不错的结果。

我看到huggingface上的demo是以单一图片的query方式输入模型：

```python
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

# use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
# use fp16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
# use cpu only
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cpu", trust_remote_code=True).eval()
# use cuda device
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cuda", trust_remote_code=True).eval()

# Specify hyperparameters for generation (No need to do this if you are using transformers>=4.32.0)
# model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-VL-Chat", trust_remote_code=True)

# 1st dialogue turn
query = tokenizer.from_list_format([
    {'image': 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'},
    {'text': '这是什么'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)
# 图中是一名年轻女子在沙滩上和她的狗玩耍，狗的品种可能是拉布拉多。她们坐在沙滩上，狗的前腿抬起来，似乎在和人类击掌。两人之间充满了信任和爱。
```

但是上面您给的链接里面说“These frames are treated as separate images and are stitched into the context. For example:”

```
{
  "question_id": "v0",
  "prompt": "<img>video_imgs_4/v0_0.jpg</img>\n<img>video_imgs_4/v0_1.jpg</img>\n<img>video_imgs_4/v0_2.jpg</img>\n<img>video_imgs_4/v0_3.jpg</img>\nQuestion: Can you identify the action taking place in the video?\nOptions: A. pretending to take something out of something\nB. pretending to take something from somewhere\nC. feigning to insert something into something\nD. simulating putting something onto something\nAnswer:"
}
```

我不太理解“stitched“，具体应该怎么做呢？

**Comment by CrazyBrick** [comment]
> we directly and uniformly sample 4 frames of the video as input in SEED-Bench

Is the image description result of directly concatenating four frames? Are there any other processing steps

**Comment by xyw7** [comment]
> > we directly and uniformly sample 4 frames of the video as input in SEED-Bench
> 
> Is the image description result of directly concatenating four frames? Are there any other processing ste

我发现按他的example，模型会回答图1xxx 图2xxx 图3xxx这样 而不是把它当作一个视频来看待

**Comment by CrazyBrick** [comment]
> > > we directly and uniformly sample 4 frames of the video as input in SEED-Bench
> > 
> > 
> > Is the image description result of directly concatenating four frames? Are there any other processing ste
> 
> 我发现按他的example，模型会回答图1xxx 图2xxx 图3xxx这样 而不是把它当作一个视频来看待

我尝试多增加一次query，但是效果一般。
`query_text = '。'.join(map(str, text_list))
    # print(query_text)
    query2 = tokenizer.from_list_format([
        {'text': f'{query_text}。这是长视频的其中几帧的描述，直接总结这个视频的内容'},
    ])`
我现在面临另外一个问题，如何在单机多卡上进行推理，因为当模型启动并计算几次之后，显存占用大概到16G了，然而我使用的是Tesla T4 15G 的卡，auto_gptq的device_map="auto"可以解决多卡加载模型，但是在计算时候会报错：
`Exception:Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:2!
`
