### ISSUE TITLE
Little problem about number

### ISSUE THREAD

**Issue by pengzhiliang** [QwenLM/Qwen-VL#6]
Congratulations！

I notice that the value of kosmos-2 in this [table](https://github.com/QwenLM/Qwen-VL#zero-shot-captioning--general-vqa) is not fair for comparison. 66.7 on flickr30k and 45.6 on vqav2dev are obtained from the model w/o instruction tuning.

We have updated the final performance on flickr30k and vqav2 on our github page [here](https://github.com/microsoft/unilm/tree/master/kosmos-2#4-image-captioning).  Specifically, kosmos-2 can achieve 80.5 on flickr30k and 51.1 on vqav2 under zeroshot setting.

Sorry for the misleading. Can you update the number for ours? 
Thanks!

**Comment by vealocia** [comment]
Hi @pengzhiliang ~
Thanks for your kind suggestion, we will add these new results to the table asap :)

**Comment by pengzhiliang** [comment]
Thanks, @vealocia.

Look forward to your paper~
