### ISSUE TITLE
Can you add a code sample for just image captioning? 

### ISSUE THREAD

**Issue by FurkanGozukara** [QwenLM/Qwen-VL#64]
Hello. I am the content producer of SECourses. AI oriented educational channel

Producing mostly about Stable Diffusion courses

https://www.youtube.com/SECourses

I am interested in image captioning capabilities of your model. I am interested in English

Can you add example code for only this task? Image captioning for Stable Diffusion training 

Is this the best fastest way? I want to generate captions locally to local images with best accuracy. Speed is second issue. 

```
image_path = 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'
response, history = model.chat(tokenizer, query=f'<img>{image_path}</img>describe the image detailed as possible', history=None)
print(response)
```

**Comment by seasnakes** [comment]
> Hello. I am the content producer of SECourses. AI oriented educational channel
> 
> Producing mostly about Stable Diffusion courses
> 
> https://www.youtube.com/SECourses
> 
> I am interested in image captioning capabilities of your model. I am interested in English
> 
> Can you add example code for only this task? Image captioning for Stable Diffusion training
> 
> Is this the best fastest way? I want to generate captions locally to local images with best accuracy. Speed is second issue.
> 
> ```
> image_path = 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'
> response, history = model.chat(tokenizer, query=f'<img>{image_path}</img>describe the image detailed as possible', history=None)
> print(response)
> ```
I also have the same requirement.

**Comment by ShadoWxShinigamI** [comment]
#136 Try this out.
