### ISSUE TITLE
swift微调时进度条显示数据量为实际数据量的1/16

### ISSUE THREAD

**Issue by yrqs** [QwenLM/Qwen-VL#66]
您好，我在使用swift微调时，训练数据集共有6367条（微调脚本执行后数据集分析函数打印的结果），batchsize设置为1，可用显卡数量指定了一张，dataset_sample为-1，但是进度条显示的数量为397（6367的1/16），请问这个正常吗？（服务器共有8张卡，但是我只指定了一张，并且nvidia-smi观测也是只用了1张）

**Comment by Xu-Chen** [comment]
用了梯度累积，需要看最终的batchsize

**Comment by yrqs** [comment]
> 

谢谢！
