### ISSUE TITLE
Evaluate Vqa dataset download

### ISSUE THREAD

**Issue by linxid** [QwenLM/Qwen-VL#68]
This a great work. I found `docvqa_val` and `docvqa_test` dataset infomation in evaluate_vqa.py. But there is not download information in EVALUATION.md, can you provide download url.

**Comment by vealocia** [comment]
Hi @linxid ! Thanks for your interest in your work and your kind remind.
We just update the document and you can find instructions for [```docvqa```](https://github.com/QwenLM/Qwen-VL/blob/master/eval_mm/EVALUATION.md#docvqa) now.

**Comment by Yuan-Lin615** [comment]
Thanks, this has helped me a lot in my work

**Comment by wufan-tb** [comment]
@vealocia hi, I evaluated the model on `docvqa_val` successfully, yet I can't evaluate it on  `docvqa_test` for it has no ground truth `answers`. could you please offer the `test_v1.0.json` file for me, the one I found from official website has no ground truth answers.

**Comment by tinytangent** [comment]
> @vealocia hi, I evaluated the model on `docvqa_val` successfully, yet I can't evaluate it on `docvqa_test` for it has no ground truth `answers`. could you please offer the `test_v1.0.json` file for me, the one I found from official website has no ground truth answers.

Hi @wufan-tb , The DocVQA dataset has public annotation for the test split. You need to submit the result file for ICDAR Robust Reading Challenge website to perform evaluation on test split.

**Comment by wufan-tb** [comment]
Oh, I see, thanks very much!
