### ISSUE TITLE
[BUG] 这个是认真的吗？是我使用的方式不对吗

### ISSUE THREAD

**Issue by FeiWard** [QwenLM/Qwen-VL#7]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-VL/assets/17875327/6dc320f2-006c-485e-a211-3c299a60b390)
他为什么这么犟，理解不了我的输入，好像一直停留在第一句了

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

有没有更新对话状态？

**Comment by simonJJJ** [comment]
Hi @FeiWard, thanks for pointing this out, could you provide the original image for us to reproduce?

**Comment by seasnakes** [comment]
> Hi @FeiWard, thanks for pointing this out, could you provide the original image for us to reproduce?
不管什么图片都会这样

**Comment by karthous** [comment]
参考论文[https://arxiv.org/pdf/2308.12966.pdf](url)的3.3 Supervised Fine-tuning部分，

> During training, we ensure the consistency between prediction and training distributions by only supervising
answers and special tokens (blue in the example), and not supervising role names or question prompts. In
this stage, we freeze the visual encoder and optimize the language model and adapter module.
