### ISSUE TITLE
💡 [REQUEST] - <batch 推理>

### ISSUE THREAD

**Issue by dengfenglai321** [QwenLM/Qwen-VL#71]
### 实现PR | Implementation PR

请问怎么执行batch推理？同时出入多张图片和prompt。返回多张图片的描述内容

### 相关Issues | Reference Issues

1

### 摘要 | Summary

1

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by zhongpeixiang** [comment]
确实是一个需求很大的功能，我现在自己实现的批量推理代码生成效果不好，主要是不确定在哪加pad token

**Comment by FangGet** [comment]
@zhongpeixiang @dengfenglai321 HF上提供了一个[qwen_generation_utils.py](https://huggingface.co/Qwen/Qwen-VL-Chat-Int4/blob/main/qwen_generation_utils.py)，循环调用里面make_context函数，组batch，然后调用generate函数和他提供的decode_token函数就好了

**Comment by beckhamchen** [comment]
> @zhongpeixiang @dengfenglai321 HF上提供了一个[qwen_generation_utils.py](https://huggingface.co/Qwen/Qwen-VL-Chat-Int4/blob/main/qwen_generation_utils.py)，循环调用里面make_context函数，组batch，然后调用generate函数和他提供的decode_token函数就好了

关键就在这里怎么组batch呢？context_tokens的长度不一样，padding效果不好
