### ISSUE TITLE
cannot access the model at modelscope and huggingface

### ISSUE THREAD

**Issue by xdhhh** [QwenLM/Qwen-VL#73]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by drockser** [comment]
+1 
![image](https://github.com/QwenLM/Qwen-VL/assets/23105024/9711b9fb-5db0-4df6-a13e-a9f40c3a1d5c)

**Comment by drockser** [comment]
+1

OSError: Qwen/Qwen-VL-Chat is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

**Comment by AlanWangyiran** [comment]
+1 seems like they have withdraw the model from hf, hopping for it to come back as soon as possible.

**Comment by Bada774** [comment]
+1

**Comment by StarCycle** [comment]
They also withdraw Qwen-7B from huggingface and modelscope. Now [https://huggingface.co/4bit](https://huggingface.co/4bit/Qwen-VL-Chat-Int4) is the only copy of the 4bit version. If anyone has the 16bit version, could you please share it with us?

**Comment by Ashwath-Shetty** [comment]
+1

**Comment by thcheung** [comment]
If you have used the model before, you may set the parameters local_files_only=True when loading the tokenizer and model.

**Comment by xiulianzw** [comment]
大家可以去魔塔社区下载模型
https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git
https://www.modelscope.cn/ccyh123/Qwen-VL.git

**Comment by Mingrui-Li** [comment]
> +1
> 
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/Qwen/Qwen-VL-Chat/resolve/main/tokenizer_config.json

+1

**Comment by yeyingdege** [comment]
> 大家可以去魔塔社区下载模型 https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git https://www.modelscope.cn/ccyh123/Qwen-VL.git

你好，请问克隆了repo之后怎么得到模型文件呢？pytorch_model-00010-of-00010.bin文件的内容是“version https://git-lfs.github.com/spec/v1
oid sha256:508bc4b5caab78e08d9961000cd00411f0e56f0f016828bcf9e78c132d960c24
size 1730968463“ 不明白怎么用

**Comment by WLpub** [comment]
from modelscope import (
    snapshot_download, AutoModelForCausalLM, AutoTokenizer, GenerationConfig
)
import torch
model_id = 'ccyh123/Qwen-VL-Chat'
revision = 'v1.0.0'
snapshot_download(model_id, revision=revision,cache_dir='/Qwen-VL-Chat')

**Comment by Tzx11** [comment]
> > 大家可以去魔塔社区下载模型 https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git https://www.modelscope.cn/ccyh123/Qwen-VL.git
> 
> 你好，请问克隆了repo之后怎么得到模型文件呢？pytorch_model-00010-of-00010.bin文件的内容是“Version https://git-lfs.github.com/spec/v1 oid sha256：508bc4b5caab78e08d9961000cd00411f0e56f0f016828bcf9e78c132d960c24 size 1730968463” 不明白怎么用

哥们，你知道怎么用模型了吗

**Comment by gigadeplex** [comment]
Well guys you don't actually need a Chinese number to register. Even if the website says so... 🤫
