### ISSUE TITLE
huggingface模型下线了？

### ISSUE THREAD

**Issue by guozhiyao** [QwenLM/Qwen-VL#74]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yotofu** [comment]
好像是没有了  刚发布finetune代码  然后huggingface就没有了  这波操作把我搞懵了

**Comment by ZJUTSong** [comment]
> 好像是没有了 刚发布finetune代码 然后huggingface就没有了 这波操作把我搞懵了

发布了finetune代码吗

**Comment by crackso** [comment]
经常打不开的。直接替换用modelscope的好了。代码修改几处就好了。基本是平移的
![image](https://github.com/QwenLM/Qwen-VL/assets/7133536/a51a6fbe-700e-483a-b4b0-9824f91f6652)
