### ISSUE TITLE
[BUG] <title>RuntimeError: "erfinv_vml_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by zhangxu33** [QwenLM/Qwen-VL#76]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我正在做qlora微调

### 复现方法 | Steps To Reproduce

1.按readme格式，准备了微调数据
2.使用int4的模型文件
3.sudo bash finetune/finetune_qlora_single_gpu.sh
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

MODEL="/home/int4/int4-qwen-vl-chat" # Qwen/Qwen-VL-Chat-Int4 Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/home/uie/Qwen-VL/my_finetune/tain.json"
#output_qwen = '/home/uie/Qwen-VL/output'
export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq
python finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --fix_vit True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --lazy_preprocess True \
    --gradient_checkpointing \
    --use_lora \
    --q_lora

4. 报错信息  return _no_grad_trunc_normal_(tensor, mean, std, a, b)
  File "/home/uie/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/torch/nn/init.py", line 46, in _no_grad_trunc_normal_
    tensor.erfinv_()
RuntimeError: "erfinv_vml_cpu" not implemented for 'Half'

### 运行环境 | Environment

```Markdown
- OS:centos7.5
- Python:3.10
- Transformers:4.33.1
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

报错信息  return _no_grad_trunc_normal_(tensor, mean, std, a, b)
  File "/home/uie/miniconda3/envs/qwen-vl/lib/python3.10/site-packages/torch/nn/init.py", line 46, in _no_grad_trunc_normal_
    tensor.erfinv_()
RuntimeError: "erfinv_vml_cpu" not implemented for 'Half'

**Comment by lukszam** [comment]
same

**Comment by sudazzk** [comment]
同问

**Comment by yazheng0307** [comment]
我也遇到了，还没解决方式

**Comment by liangzhiyuanCV** [comment]
我也遇到了同样的问题，还没有解决

**Comment by Ashoka74** [comment]
Same issue here!

**Comment by kenJPG** [comment]
I fixed it by using GPU for Int-4 QwenVL. CPU will not work because Int-4 QwenVL is quantized, and only works on GPU.

```
	model = AutoModelForCausalLM.from_pretrained(
		model_dir,
		device_map='auto', # <- important line here
		trust_remote_code=True,
		resume_download=True,
	).eval()
```

**Comment by lyhgalaxy** [comment]
在finetune.py将device_map设置成auto或许能解决，但我使用3090还是会报显存不足问题
![image](https://github.com/QwenLM/Qwen-VL/assets/42365371/8b04cb3e-3829-4590-abd6-e0f5d9585947)

**Comment by lyhgalaxy** [comment]
在finetune.py将device_map设置成auto或许能解决，但我使用3090还是会报显存不足问题
![image](https://github.com/QwenLM/Qwen-VL/assets/42365371/8b04cb3e-3829-4590-abd6-e0f5d9585947)

**Comment by zhangxu33** [comment]
你是用int4模型跑的qlora脚本吗，我试一试

**Comment by lyhgalaxy** [comment]
> 你是用int4模型跑的qlora脚本吗，我试一试

是的 sh finetune/finetune_qlora_single_gpu.sh

**Comment by midasklr** [comment]
我修改auto后又报错：
ValueError: Attempting to unscale FP16 gradients.
我也是3090

**Comment by tanghaom** [comment]
我修改auto后也是报错：
ValueError: Attempting to unscale FP16 gradients.
3090和V100都试过了。

还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错：
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by Ashoka74** [comment]
I faced the same error

`ValueError: Attempting to unscale FP16 gradients.`

 on an RTX A6000 after changing auto to 'cuda' in finetune.py

**Comment by khushboo-anand0909** [comment]
"ValueError: Attempting to unscale FP16 gradients."  Was this issue resolved?

**Comment by CrazyBrick** [comment]
> "ValueError: Attempting to unscale FP16 gradients." Was this issue resolved?

was this issue solved?

**Comment by Mingrui-Li** [comment]
我V100的卡可以正确lora微调了，
![output](https://github.com/QwenLM/Qwen-VL/assets/20225895/a52979e6-395d-4782-84ef-db9656507e7e)

"erfinv_vml_cpu" not implemented for 'Half'  这个错误，需要修改  --fp16 False \ 

我debug的时候发现 device_map是none，修改了device_map 的方法

`device_map = {"": int(os.environ.get("LOCAL_RANK") or 0)} `

model的方法我也给改了

`model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        config=config,
        cache_dir=training_args.cache_dir,
        device_map=device_map,
        trust_remote_code=True,
        #quantization_config=GPTQConfig(
        #    bits=4, disable_exllama=True
        #)
        #if training_args.use_lora and lora_args.q_lora
        #else None,
    )
`
能正常lora的代码我上传 https://github.com/Mingrui-Li/Qwen-VL-Lora-Model.git 上去了，供参考

**Comment by a2382625920** [comment]
> 我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients. 3090和V100都试过了。
> 
> 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError： probability tensor contains either ， or element < 0`inf``nan`

我也是关闭了FP16，我使用我自己的数据进行微调，虽然微调成功，但是遇到了同样无法推理的问题，但不是你这样的报错，我的checkpoint并不能被识别

**Comment by a2382625920** [comment]
> 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。
> 
> 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:

**Comment by tanghaom** [comment]
> > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> 
> 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:

用modelscope的swift就可以了
https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary
https://github.com/modelscope/swift/tree/main/examples/pytorch/llm

**Comment by a2382625920** [comment]
> > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > 
> > 
> > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> 
> 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm

非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调
https://huggingface.co/Qwen/Qwen-VL-Chat-Int4
问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by tanghaom** [comment]
> > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > 
> > > 
> > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > 
> > 
> > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> 
> 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的

**Comment by a2382625920** [comment]
> > > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > > 
> > > > 
> > > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > > 
> > > 
> > > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> > 
> > 
> > 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> 
> 哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的

好滴，我去试一下再过来反馈

**Comment by GUOGUO-lab** [comment]
> > > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > > 
> > > > 
> > > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > > 
> > > 
> > > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> > 
> > 
> > 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> 
> 哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的

请问使用swift进行微调时，数据格式和本项目中的数据格式保持一致吗？我看swift项目里的微调数据格式（llm下的）好像不太一样

**Comment by tanghaom** [comment]
> > > > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > > > 
> > > > > 
> > > > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > > > 
> > > > 
> > > > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> > > 
> > > 
> > > 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > 
> > 
> > 哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的
> 
> 请问使用swift进行微调时，数据格式和本项目中的数据格式保持一致吗？我看swift项目里的微调数据格式（llm下的）好像不太一样

我是在swift那边自定义了数据集，旧版的dataset.py是在样例里的src/utils下，翻了下swift的仓库现在是移到包里了 
 https://github.com/modelscope/swift/blob/main/swift/llm/utils/dataset.py，没具体看 不知道调用传参有没有变化。
给你个样例参考吧，用这个项目里的数据集格式
```
def get_custom_dataset() -> Tuple[HfDataset, HfDataset]:
    with open('xxxxx/data.json') as f:
        datas = json.load(f)
    query = []
    response = []
    random.shuffle(datas)
    for data in datas:
        query.append(data['conversations'][0]['value'])
        response.append(data['conversations'][1]['value'])
    split_len = int(len(query) * 0.9)
    train_dataset = HfDataset.from_dict({'query': query[:split_len], 'response': response[:split_len]})
    val_dataset = HfDataset.from_dict({'query': query[split_len:], 'response': response[split_len:]})
    return tuple([train_dataset, val_dataset])
```

**Comment by a2382625920** [comment]
> > > > > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > > > > 
> > > > > > 
> > > > > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > > > > 
> > > > > 
> > > > > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> > > > 
> > > > 
> > > > 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > 
> > > 
> > > 哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的
> > 
> > 
> > 请问使用swift进行微调时，数据格式和本项目中的数据格式保持一致吗？我看swift项目里的微调数据格式（llm下的）好像不太一样
> 
> 我是在swift那边自定义了数据集，旧版的dataset.py是在样例里的src/utils下，翻了下swift的仓库现在是移到包里了 [https://github.com/modelscope/swift/blob/main/swift/llm/utils/dataset.py，没具体看](https://github.com/modelscope/swift/blob/main/swift/llm/utils/dataset.py%EF%BC%8C%E6%B2%A1%E5%85%B7%E4%BD%93%E7%9C%8B) 不知道调用传参有没有变化。 给你个样例参考吧，用这个项目里的数据集格式
> 
> ```
> def get_custom_dataset() -> Tuple[HfDataset, HfDataset]:
>     with open('xxxxx/data.json') as f:
>         datas = json.load(f)
>     query = []
>     response = []
>     random.shuffle(datas)
>     for data in datas:
>         query.append(data['conversations'][0]['value'])
>         response.append(data['conversations'][1]['value'])
>     split_len = int(len(query) * 0.9)
>     train_dataset = HfDataset.from_dict({'query': query[:split_len], 'response': response[:split_len]})
>     val_dataset = HfDataset.from_dict({'query': query[split_len:], 'response': response[split_len:]})
>     return tuple([train_dataset, val_dataset])
> ```

是的，我在构建自己的数据集的时候也出现了问题，多模态的数据格式比纯语言模型要复杂，你们是怎么在文件中构建Qwen-VL的数据集的呢

**Comment by GUOGUO-lab** [comment]
> > > > > > > 我修改auto后也是报错： ValueError: Attempting to unscale FP16 gradients. 3090和V100都试过了。我修改auto后也是报错： ValueError： Trying to unscale FP16 gradients.3090和V100都试过了。
> > > > > > > 还试了V100上关闭fp16训练，训练能正常跑，结束后跑推理报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > > > > 
> > > > > > 
> > > > > > 你好，请问你遇到的问题解决了吗，可以正常推理了吗，我现在遇到了这样一个错误RuntimeError: Error(s) in loading state_dict for QWenLMHeadModel:
> > > > > 
> > > > > 
> > > > > 用modelscope的swift就可以了 https://www.modelscope.cn/models/qwen/Qwen-VL-Chat/summary https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
> > > > 
> > > > 
> > > > 非常感谢，但是我是直接使用的官方用AutoGPT量化框架量化的模型Qwen-VL-Chat-INT4直接进行的qlora微调 https://huggingface.co/Qwen/Qwen-VL-Chat-Int4 问题已经解决了，使用了官方的推理方法，但是在读取完模型准备进行预测时又有一个新的问题 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> > > 
> > > 
> > > 哈哈 你这个不就是我之前碰到的问题嘛，我上面发的意思是训练测试推理都用modelscope的。我之前试了是没问题的
> > 
> > 
> > 请问使用swift进行微调时，数据格式和本项目中的数据格式保持一致吗？我看swift项目里的微调数据格式（llm下的）好像不太一样
> 
> 我是在swift那边自定义了数据集，旧版的dataset.py是在样例里的src/utils下，翻了下swift的仓库现在是移到包里了 [https://github.com/modelscope/swift/blob/main/swift/llm/utils/dataset.py，没具体看](https://github.com/modelscope/swift/blob/main/swift/llm/utils/dataset.py%EF%BC%8C%E6%B2%A1%E5%85%B7%E4%BD%93%E7%9C%8B) 不知道调用传参有没有变化。 给你个样例参考吧，用这个项目里的数据集格式
> 
> ```
> def get_custom_dataset() -> Tuple[HfDataset, HfDataset]:
>     with open('xxxxx/data.json') as f:
>         datas = json.load(f)
>     query = []
>     response = []
>     random.shuffle(datas)
>     for data in datas:
>         query.append(data['conversations'][0]['value'])
>         response.append(data['conversations'][1]['value'])
>     split_len = int(len(query) * 0.9)
>     train_dataset = HfDataset.from_dict({'query': query[:split_len], 'response': response[:split_len]})
>     val_dataset = HfDataset.from_dict({'query': query[split_len:], 'response': response[split_len:]})
>     return tuple([train_dataset, val_dataset])
> ```

![image](https://github.com/QwenLM/Qwen-VL/assets/56341774/071b32e0-9bca-4c6e-9ae1-459e61ce5ac2)
我看swift这里面有个格式，不过他只是语言模型的qa，这里如果改成多模态，是模仿本项目下往里面加<img>img_path</img>吗？

https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md

**Comment by tanghaom** [comment]
@GUOGUO-lab @a2382625920 
对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用<ref>和<box>来描述目标框

**Comment by GUOGUO-lab** [comment]
> @GUOGUO-lab @a2382625920 `对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用 <ref> 和 <box> 来描述目标框`

@a2382625920 已在V100完成基于Swift的微调与推理，可以按照Swift中的数据格式进行自定义多模态数据的使用，就是上面的文档里作者推荐的方案，注意调整sft.sh中的参数，V100在刚启动微调时有几率出现“Unable to find a valid cuDNN algorithm to run convolution”，推测是显存或者算力的问题，观察到微调开始的第一个epoch显存与算力占用非常大。

再次感谢 @tanghaom 您的协助。

**Comment by Junxiao-Ma** [comment]
> 我V100的卡可以正确lora微调了， ![output](https://private-user-images.githubusercontent.com/20225895/278508749-a52979e6-395d-4782-84ef-db9656507e7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTk5MjgsIm5iZiI6MTcxMDY1OTYyOCwicGF0aCI6Ii8yMDIyNTg5NS8yNzg1MDg3NDktYTUyOTc5ZTYtMzk1ZC00NzgyLTg0ZWYtZGI5NjU2NTA3ZTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA3MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Y2EzNmJhNWNjNTNlOWQyZTQxMDY3NjFjZWVhMWQ1NWI4ZDZiYjE1YmY1MDE3OGE0YTllOWY3ODYzYmU5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.joJrMQhhMYg0gPnA3_mJFuodU9r1lKOpnGUsmQe0EN4)
> 
> "erfinv_vml_cpu" not implemented for 'Half' 这个错误，需要修改 --fp16 False \
> 
> 我debug的时候发现 device_map是none，修改了device_map 的方法
> 
> `device_map = {"": int(os.environ.get("LOCAL_RANK") or 0)} `
> 
> model的方法我也给改了
> 
> `model = transformers.AutoModelForCausalLM.from_pretrained( model_args.model_name_or_path, config=config, cache_dir=training_args.cache_dir, device_map=device_map, trust_remote_code=True, #quantization_config=GPTQConfig( # bits=4, disable_exllama=True #) #if training_args.use_lora and lora_args.q_lora #else None, ) ` 能正常lora的代码我上传 https://github.com/Mingrui-Li/Qwen-VL-Lora-Model.git 上去了，供参考

I have a question: Why your loss is 0.0 after one step? @Mingrui-Li

**Comment by MayCloud052** [comment]
> @GUOGUO-lab @a2382625920 `对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用 <ref> 和 <box> 来描述目标框`

您好~想请问一下用 <ref> 和 <box> 来描述目标框的模板具体是什么样的呢？我在项目里没有看到这种描述目标框的格式。

**Comment by MayCloud052** [comment]
> @GUOGUO-lab @a2382625920 `对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用 <ref> 和 <box> 来描述目标框`

@tanghaom 您好~我想请问一下用 <ref> 和 <box> 来描述目标框的模板是什么样的呢？我在这个项目里没有看到用 <ref> 和 <box> 来描述目标框的格式。

**Comment by tanghaom** [comment]
> > @GUOGUO-lab @a2382625920 `对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用 <ref> 和 <box> 来描述目标框`
> 
> @tanghaom 您好~我想请问一下用 ref 和 box 来描述目标框的模板是什么样的呢？我在这个项目里没有看到用 ref 和 box 来描述目标框的格式。

https://github.com/QwenLM/Qwen-VL/blob/master/README_CN.md#%E5%BE%AE%E8%B0%83
![image](https://github.com/QwenLM/Qwen-VL/assets/48461500/f793761d-4fc7-4f24-a833-60b68f084fe0)

**Comment by MayCloud052** [comment]
> > > @GUOGUO-lab @a2382625920 `对的，query里图片就跟这个项目里一样用 <img>path_to_img.png</img> 的格式描述就行，response里也是跟这个项目里的一样，同样可以用 <ref> 和 <box> 来描述目标框`
> > 
> > 
> > @tanghaom 您好~我想请问一下用 ref 和 box 来描述目标框的模板是什么样的呢？我在这个项目里没有看到用 ref 和 box 来描述目标框的格式。
> 
> https://github.com/QwenLM/Qwen-VL/blob/master/README_CN.md#%E5%BE%AE%E8%B0%83 ![image](https://private-user-images.githubusercontent.com/48461500/320406090-f793761d-4fc7-4f24-a833-60b68f084fe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDgzMDIsIm5iZiI6MTcxMjY0ODAwMiwicGF0aCI6Ii80ODQ2MTUwMC8zMjA0MDYwOTAtZjc5Mzc2MWQtNGZjNy00ZjI0LWE4MzMtNjBiNjhmMDg0ZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNWIwOTliOTE1OWNmMzIzY2E3MzI1OGY1MDk1ODQ4ZWY0OTliODI4YTJhYTg0ZmEwMjhmNDM3YTI2NTBmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qpLAQLA1WFzUkyvS6HQen_wtUaXSJUQlVN7TiTX_XtY)

好的，谢谢您！
