### ISSUE TITLE
Qwen-VL-Chat训练数据集

### ISSUE THREAD

**Issue by Crystalxd** [QwenLM/Qwen-VL#77]
请问Qwen-VL-Chat有开源的数据集可以进行训练吗？或者是基于什么类型的数据集进行训练的？打算加一些进去进行微调，以尽量避免灾难性遗忘。

**Comment by Rickylht** [comment]
开源的数据文章里有写都能下。最珍贵的肯定是自己爬的数据，肯定不会给。

**Comment by ZhihuaGao** [comment]
@ShuaiBai623 针对出现的灾难性遗忘问题，有什么好的建议嘛

**Comment by demo123attack** [comment]
> 开源的数据文章里有写都能下。最珍贵的肯定是自己爬的数据，肯定不会给。

文章里提了用了哪些开源的数据吗
