### ISSUE TITLE
能否提供模型下载链接？

### ISSUE THREAD

**Issue by shengyuwoo** [QwenLM/Qwen-VL#78]
这个开源工作太棒了，但是目前程序加载的Qwen-VL模型是默认方式下载的，网络稍微不行就一直报错。大佬是否可以提供huaggingface空间的模型下载链接呢？ 有的话超级超级感谢。

**Comment by 2132660698** [comment]
git clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git 
git clone https://www.modelscope.cn/ccyh123/Qwen-VL.git

**Comment by LOGIC-10** [comment]
原本是可以在huggingface直接下载的

**Comment by shengyuwoo** [comment]
在modelscope上还是不能下载啊，没有开放下载权限？ 只能查看，没有下载选项啊。

**Comment by shengyuwoo** [comment]
> git clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git git clone https://www.modelscope.cn/ccyh123/Qwen-VL.git

在modelscope上还是不能下载啊，没有开放下载权限？ 只能查看，没有下载选项啊。

**Comment by shengyuwoo** [comment]
OK，我已经根据下面两个链接直接完成了下载，直接在本地电脑git 拉取就行了，时间有点长，请耐心等待，谢谢答疑的朋友们，棒棒的！
git clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git
git clone https://www.modelscope.cn/ccyh123/Qwen-VL.git

**Comment by Byakuya-zi** [comment]
> OK，我已经根据下面两个链接直接完成了下载，直接在本地电脑git 拉取就行了，时间有点长，请耐心等待，谢谢答疑的朋友们，棒棒的！ git clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git git clone https://www.modelscope.cn/ccyh123/Qwen-VL.git

请问大概需要下载多久呢，我现在卡在了
```
Cloning into 'Qwen-VL-Chat'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 50 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (50/50), 7.54 MiB | 9.12 MiB/s, done.
```

**Comment by Byakuya-zi** [comment]
解决了，需要用git lfs clone

**Comment by shengyuwoo** [comment]
> > OK，我已经根据下面两个链接直接完成了下载，直接在本地电脑git 拉取就行了，时间有点长，请耐心等待，谢谢答疑的朋友们，棒棒的！ git clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git git clone https://www.modelscope.cn/ccyh123/Qwen-VL.git
> 
> 请问大概需要下载多久呢，我现在卡在了
> 
> ```
> Cloning into 'Qwen-VL-Chat'...
> remote: Enumerating objects: 50, done.
> remote: Counting objects: 100% (50/50), done.
> remote: Compressing objects: 100% (49/49), done.
> remote: Total 50 (delta 5), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (50/50), 7.54 MiB | 9.12 MiB/s, done.
> ```

没具体看过时间，不过确实需要挺长时间的。

**Comment by zhangxu33** [comment]
![a64d79a0a703346848cebe81400dcdde](https://github.com/QwenLM/Qwen-VL/assets/88977298/78583531-5959-4db9-8f6c-812a40e06b5f)
1.9G    Qwen-VL-Chat/.git/lfs/objects/5f

**Comment by zhangxu33** [comment]
git lfs clone下载的正确吗？我这用的git lfs clone https://www.modelscope.cn/ccyh123/Qwen-VL-Chat.git，这些权重文件还是很小，.git里边倒是有很多约2G的文件
