### ISSUE TITLE
Is it possible to know how the image recognition works?

### ISSUE THREAD

**Issue by rainblkawsd** [QwenLM/Qwen-VL#8]
### 摘要 | Summary

Is it possible to include it in the documentation?

### 基本示例 | Basic Example

N/A

### 缺陷 | Drawbacks

N/A

**Comment by ShuaiBai623** [comment]
We have added an initial version of a technical report that introduces our method. Please refer to https://arxiv.org/pdf/2308.12966.pdf for further details.
