### ISSUE TITLE
[BUG] <title> 图文的输入可以交换顺序吗？

### ISSUE THREAD

**Issue by sudazzk** [QwenLM/Qwen-VL#83]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

目前用样例测试：
prompt = [
    {'text': 'Based on the photo, which floor is the Department of Otorhinolaryngology on?'},
    {'image': './Qwen-VL-master/assets/mm_tutorial/Hospital.jpg'},
]
返回结果是：Received.

我的输入有文字、图片、prompt，可以按这个顺序输入到模型进行推理吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ShuaiBai623** [comment]
可以按照文字、图片、prompt进行推理，不过更稳定的方式是[图，文],[图，图，文]

**Comment by sudazzk** [comment]
ok

**Comment by dydxdt** [comment]
> 可以按照文字、图片、prompt进行推理，不过更稳定的方式是[图，文],[图，图，文]

@ShuaiBai623 想请问微调时训练集数据需要把<img>{img_path}</img>放在问句的最前面吗？还是这个位置不重要呢？不太懂求解答～感谢

**Comment by ShuaiBai623** [comment]
最好把{img_path}放在问句的最前面，这个和训练一致
