### ISSUE TITLE
How to infer by finetuned model

### ISSUE THREAD

**Issue by hnsywangxin** [QwenLM/Qwen-VL#87]
Hi, thanks for your amazing work.
Now, I 'm currently encountering a slight issue with your fine-tuning script:https://github.com/QwenLM/Qwen-VL/blob/master/README_CN.md#lora
how do I use the fine-tuned model for inference? Can you assist me with this? Thank you

**Comment by hnsywangxin** [comment]
model = AutoPeftModelForCausalLM.from_pretrained("your checkpoint path",trust_remote_code=True, device_map=device_map).eval()
or 
```
    model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        # torch_dtype=torch.float16,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
    )
model = PeftModel.from_pretrained(model, "your checkpoint path", device_map=device_map).eval()
    model.generation_config = GenerationConfig.from_pretrained(
        args.checkpoint_path,torch_dtype=torch.float16, trust_remote_code=True, resume_download=True
    )
```
but I have another problem:RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by Jo-Pan** [comment]
I solved the problem by setting device map to a specific GPU. It looks like the 'auto' mode automatically distribute the computation to all GPUs and the computation is messed up because of that.
`model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map=2,
    trust_remote_code=True
).eval()`

**Comment by hnsywangxin** [comment]
> I have the same problem. Finetuned with lora, single_gpu.
> 
> I solved the problem by setting device map to a specific GPU. It looks like the 'auto' mode automatically distribute the computation to all GPUs and the computation is messed up because of that.
> 
> ```
> model = AutoPeftModelForCausalLM.from_pretrained(
>     path_to_adapter, # path to the output directory
>     device_map=2,
>     trust_remote_code=True
> ).eval()
> ```

Thanks for your reply, I have tried it according to your method, but it still hasn't been resolved.

**Comment by Ashwath-Shetty** [comment]
how did you guys finetune? it just stops everything & throws below output for me. it doesn't even have any error message. any idea, what's wrong?

i'm on an aws notebook instance which has 24gb gpu.

output:
```
py310) [ec2-user@ip-172-16-77-3 Qwen-VL]$ sh finetune/finetune_lora_single_gpu.sh
[2023-09-14 11:36:31,195] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
finetune/finetune_lora_single_gpu.sh: line 38: 18541 Killed                  python finetune.py --model_name_or_path $MODEL --data_path $DATA --bf16 True --fix_vit True --output_dir "output_qwen" --num_train_epochs 5 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 1000 --save_total_limit 10 --learning_rate 1e-5 --weight_decay 0.1 --adam_beta2 0.95 --warmup_ratio 0.01 --lr_scheduler_type "cosine" --logging_steps 1 --report_to "none" --model_max_length 2048 --lazy_preprocess True --gradient_checkpointing --use_lora
```

**Comment by hnsywangxin** [comment]
I have solved this problem.
Reason:
A GPU that is not based on the Ampere architecture does not support BF16 and will automatically convert it to FP16. This can result in a training loss of 0, which can lead to issues during inference.
Solutions: 
Configure training with BF16 format

**Comment by zhrRunner** [comment]
> Hello, I fine-tuned Qwen-VL-Chat with the script "fine-tune_lora_single_gpu.sh" on my custom dataset. However, while trying to use it for inference, I'm encountering an error: "AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'". Can anyone help me with this issue?

I have the same question as you, Have you solved it？

**Comment by zhrRunner** [comment]
> Hello, I fine-tuned Qwen-VL-Chat with the script "fine-tune_lora_single_gpu.sh" on my custom dataset. However, while trying to use it for inference, I'm encountering an error: "AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'". Can anyone help me with this issue? ![Capture d'écran 2024-03-01 174656](https://private-user-images.githubusercontent.com/151547527/309345921-47d0540d-576a-4f50-be8c-adb1b2c1c07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTA0MDIsIm5iZiI6MTcxMzU5MDEwMiwicGF0aCI6Ii8xNTE1NDc1MjcvMzA5MzQ1OTIxLTQ3ZDA1NDBkLTU3NmEtNGY1MC1iZThjLWFkYjFiMmMxYzA3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwNTE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzhmNTIzNDIwOWNiNTlkY2NhNzY3Mzg2YzA2MTBmYWViZTY5NDBkNzc2NjkyNmViYzVmODQ4YzA3OTkyNmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q0sx8A5BfrmBaIHEdiS46CDZJ-ZldbFiKEvLkWO9ANw)

ops, I found it
you can just "put super().__init__(**kwargs)" under self.IMAGE_ST
and then  chmod 444 tokenization_qwen.py
<img width="652" alt="image" src="https://github.com/QwenLM/Qwen-VL/assets/125541805/89c9b439-7d8b-458f-ac80-0dd14021f733">

**Comment by GXKIM** [comment]
> "put super().**init**(**kwargs

hhh It’s not working for me
