### ISSUE TITLE
[BUG] <title> 关于VQA训练数据的疑问

### ISSUE THREAD

**Issue by JamesHujy** [QwenLM/Qwen-VL#88]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

请问Qwen-VL在第二阶段是否使用了TextVQA的训练集呢，论文中的Table 3里面并没有提到使用TextVQA数据，但在使用Qwen-VL在TextVQA测试集上进行inference时，模型会多次输出“answering does not require reading text in the image”，怀疑在训练阶段使用了TextVQA的训练集，想确认一下是否使用

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by tinytangent** [comment]
您好，我们确实在第二阶段使用了TextVQA中的样本，抱歉论文中这一点没有解释清楚，我们之后将会更新论文。
此外，据我所知，“answering does not require reading text in the image”似乎并不是TextVQA中的样本，可以提供一下您使用的图像和prompt方便我们排查么？谢谢您！
