### ISSUE TITLE
using GPT4 for evaluating

### ISSUE THREAD

**Issue by zhangshengnan96** [QwenLM/Qwen-VL#9]
could GPT4 API support image uploading?  Could you share with us some details about it?

**Comment by ShuaiBai623** [comment]
We are using GPT4 with only text inputs, and we replace image content inputs with manual annotations, following the approach outlined in https://github.com/QwenLM/Qwen-VL/blob/master/touchstone/README.md. We will soon release a more detailed technical report.

**Comment by ShuaiBai623** [comment]
Thanks for your attention, we add more details in the [paper](https://arxiv.org/abs/2308.16890). 
The evaluation script is provided at this [repo](https://github.com/OFA-Sys/TouchStone)

**Comment by zhangshengnan96** [comment]
> Thanks for your attention, we add more details in the [paper](https://arxiv.org/abs/2308.16890). The evaluation script is provided at this [repo](https://github.com/OFA-Sys/TouchStone)



> We are using GPT4 with only text inputs, and we replace image content inputs with manual annotations, following the approach outlined in https://github.com/QwenLM/Qwen-VL/blob/master/touchstone/README.md. We will soon release a more detailed technical report.

Thanks a lot! Really appreciate this excellent work and the contributions you and your team have made to the open-source community.
