### ISSUE TITLE
 Max retries exceeded with url: /Qwen-VL/assets/SimSun.ttf

### ISSUE THREAD

**Issue by WLpub** [QwenLM/Qwen-VL#90]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat/tokenization_qwen.py", line 33, in <module>
    ttf = requests.get("https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/SimSun.ttf")
  File "/root/miniconda3/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='qianwen-res.oss-cn-beijing.aliyuncs.com', port=443): Max retries exceeded with url: /Qwen-VL/assets/SimSun.ttf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc53fef3ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
(base) 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by BoyaWu10** [comment]
I encounter the same problem and work around by:
- loading Qwen-VL-Chat from local disk
- downloading `SimSun.ttf` myself
- updating the [FONT_PATH](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/2562bb20c375615e99b422d425066af6939d165e/tokenization_qwen.py#L30) to the location my `SimSun.ttf`.

**Comment by tommy3266** [comment]
> I encounter the same problem and work around by:
> 
> * loading Qwen-VL-Chat from local disk
> * downloading `SimSun.ttf` myself
> * updating the [FONT_PATH](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/2562bb20c375615e99b422d425066af6939d165e/tokenization_qwen.py#L30) to the location my `SimSun.ttf`.

where is your SimSun.ttf location?  can you tell me ,tks

**Comment by stomachacheGE** [comment]
> > I encounter the same problem and work around by:
> > 
> > * loading Qwen-VL-Chat from local disk
> > * downloading `SimSun.ttf` myself
> > * updating the [FONT_PATH](https://huggingface.co/Qwen/Qwen-VL-Chat/blob/2562bb20c375615e99b422d425066af6939d165e/tokenization_qwen.py#L30) to the location my `SimSun.ttf`.
> 
> where is your SimSun.ttf location? can you tell me ,tks

Download SimSun.ttf to anywhere on your local disk, and update FONT_PATH in `tokenization_qwen.py` to your file location.
