### ISSUE TITLE
[咨询] 单卡 v100 无法推理 qwen-vl-7b 模型

### ISSUE THREAD

**Issue by hhaAndroid** [QwenLM/Qwen-VL#93]
## v100 cuda oom
你好，我看 demo 里面有如下代码：

```python
# 打开bf16精度，A100、H100、RTX3060、RTX3070等显卡建议启用以节省显存
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL", device_map="auto", trust_remote_code=True, bf16=True).eval()
# 打开fp16精度，V100、P100、T4等显卡建议启用以节省显存
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL", device_map="auto", trust_remote_code=True, fp16=True).eval()
```
但是我实测发现其实 v100 加载模型会 oom，请问 32G V100 只能用 cpu 加载吗？

## v100 cpu 参数错误

然后我想用一下cpu 模式，因此采用了如下代码

```python
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cpu", trust_remote_code=True).eval()
```
但是报错提示： ValueError: If passing a string for `device_map`, please choose 'auto', 'balanced', 'balanced_low_0' or 'sequential'.

因此我直接去掉了 device_map 参数，理论上就是应该在 cpu 下

## v100 cpu 报错

我采用上述的代码运行，结果发现不支持 cpu 运行，报错如下：

```python
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```
这是因为 conv 不支持 half 计算，因此还是要改改

## v100 cpu fp32 结果不一致

我最终换成 cpu fp32 跑了，虽然很慢，但是跑通了，但是结果好像不一样

```python
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL", trust_remote_code=True, fp32=True).eval()
```

![image](https://github.com/QwenLM/Qwen-VL/assets/17425982/51bac052-ddf7-4b6f-8a6e-727b14b11423)

会多一个前缀，请问这是合理的吗？

**Comment by Wang-Xiaodong1899** [comment]
hi @hhaAndroid , try the code:
```
model = AutoModelForCausalLM.from_pretrained(base_model, device_map="cuda", trust_remote_code=True).eval()
```
It can infer normally.
