### ISSUE TITLE
是否支持将Qwen-7b大语言模型替换为LLaMA-7b模型作为LLM模块？

### ISSUE THREAD

**Issue by shengyuwoo** [QwenLM/Qwen-VL#94]
你好，请问Qwen-VL是否支持将LLM部分的Qwen-7b更换为LLaMA-b进行微调训练？因为我这边自己训练了一个LLaMA-7b的，想利用你这个框架对比一下效果。

**Comment by ShuaiBai623** [comment]
直接使用应该是有问题的，如果使用大量数据微调我们没有尝试过，如果您有兴趣，很期待您的结果。

**Comment by qazzombie** [comment]
> 你好，请问Qwen-VL是否支持将LLM部分的Qwen-7b更换为LLaMA-b进行微调训练？因为我这边自己训练了一个LLaMA-7b的，想利用你这个框架对比一下效果。

你好，请问你有尝试这个实验不，效果怎么样，直接在任务上微调行不
