### ISSUE TITLE
results of eval_caption in bsz=1/bsz=8 are different, is it a numerical precision problem?

### ISSUE THREAD

**Issue by MingsYang** [QwenLM/Qwen-VL#95]
I used the eval_capion.py script in eval_mm to run a bsz = 1 and bsz = 8 inference on flickrs30k, and got different answer for serveral samples, and I checked the input_ids and attention_mask which were fed into the model, they were identical in bsz = 1 ans bsz = 8.
![image](https://github.com/QwenLM/Qwen-VL/assets/15760556/2f882526-62c3-4af8-8f4f-cd4936bc02de)

I wonder if this is a numerical precision problem, have you met this problem before.

**Comment by jinze1994** [comment]
Have you set

**Comment by jinze1994** [comment]
Have you set

**Comment by jinze1994** [comment]
Have you already set the greedy mode for inference in the following way?
```
model.generation_config = GenerationConfig.from_pretrained('Qwen/Qwen-VL-Chat', trust_remote_code=True)
model.generation_config.top_p = 0.01
```

**Comment by MingsYang** [comment]
I used the default eval_caption.py script in eval_mm, which set do_sample=False, is it not enough?
![image](https://github.com/QwenLM/Qwen-VL/assets/15760556/6ea68faa-8705-4ebd-9166-9a49cadc29c0)
