### ISSUE TITLE
[BUG] "erfinv_cuda" not implemented for 'BFloat16' in finetune_ds.sh with zero3

### ISSUE THREAD

**Issue by BoyaWu10** [QwenLM/Qwen-VL#96]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

After changing deepspeed configuration to `--deepspeed finetune/ds_config_zero3.json` in `finetune/finetune_ds.sh`, following error occurred:

```
RuntimeError: "erfinv_cuda" not implemented for 'BFloat16'
```

### 期望行为 | Expected Behavior

Training without error or any workaround.

### 复现方法 | Steps To Reproduce

MODEL="/path/to/Qwen-VL-Chat"
DATA="/path/to/data.json"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --fix_vit True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed finetune/ds_config_zero3.json

### 运行环境 | Environment

```Markdown
- OS: 18.04
- Python: 3.10
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by suay1113** [comment]
我也是，在A40上遇到了这个问题，在A100上没出现。具体原因没排查出来

**Comment by qnguyen3** [comment]
same problem

**Comment by huizhang0110** [comment]
同样的问题，有人解决了吗？

**Comment by Mingrui-Li** [comment]
试试把 --bf16 True  改成  --fp16 True

**Comment by ShuaiBai623** [comment]
也可以删除visual.py的初始化部分 https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/visual.py#:~:text=self.apply(self._init_weights)

**Comment by ZhihuaGao** [comment]
> 试试把 --bf16 True 改成 --fp16 True

bug why?

**Comment by ZhihuaGao** [comment]
> 也可以删除visual.py的初始化部分 https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/visual.py#:~:text=self.apply(self._init_weights)

尝试了，并没有用

**Comment by Xiongjiba** [comment]
相同的问题

**Comment by entropy2333** [comment]
same problem on RTX 3090

**Comment by peace-zy** [comment]
https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/visual.py

**Comment by chensongcan** [comment]
我也遇到这个问题，有人解决了吗

**Comment by yihp** [comment]
请问有人解决了吗？

**Comment by mokby** [comment]
same issue here, anyone solved?
