### ISSUE TITLE
💡 [REQUEST] - <title>Qwen-VL-Chat-1.1

### ISSUE THREAD

**Issue by lj163ucas** [QwenLM/Qwen-VL#97]
### 摘要 | Summary

Where to download the weights of Qwen-VL-Chat-1.1?
The link in the readme seems to be Qwen-VL-Chat-1.0

### 基本示例 | Basic Example

None

### 缺陷 | Drawbacks

None

**Comment by ShuaiBai623** [comment]
提供的链接被直接更新为新的模型了

**Comment by dlutwy** [comment]
> 提供的链接被直接更新为新的模型了

@ShuaiBai623 
量化版的（Qwen-VL-Chat-Int4） 是基于 1.1 量化的吗？ 我看modelscope 以及 hugging face 关于模型权重的更新是在8月底
