### ISSUE TITLE
关于论文中的Position-aware Vision-Language Adapter模块的代码实现位置疑惑

### ISSUE THREAD

**Issue by Lucky-BenXie** [QwenLM/Qwen-VL#98]
你好，就是我有关注到论文中提到的Position-aware Vision-Language Adapter模块，但是我在查看代码的时候没有找到相应的实现位置，能帮忙解答具体实现的位置在哪？

**Comment by Wang-Xiaodong1899** [comment]
Hi @Lucky-BenXie , if you review the detailed code in HuggingFace, you can find this module at https://huggingface.co/Qwen/Qwen-VL/blob/main/visual.py#L382, and this module changes the input image tokens to 256 tokens. Hope this helps you understand.

**Comment by supermancmk** [comment]
I also get a problem when running finetune_ds.sh with ---deepspeed finetune/ds_config_zero3.json and --fp16 True  whatever fully fine-tune or Lora . AssertionError: Only Support Self-Attention Currently. Is this a bug?

**Comment by Wang-Xiaodong1899** [comment]
hi @supermancmk. I think you can delete this assert code line, because the query and key tensor are always same in the VisionAttention. However, skip this bug, I met another bug:

**File "/opt/conda/envs/qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 306, in fetch_sub_module
    assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
AssertionError: {'id': 853, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}**

I found the related issues in DeepSpeed Repo, and I tried to back to `transformers=4.31.0` but it didn't work. Sad!

**Comment by lucasjinreal** [comment]
NO, it works as expected

**Comment by Wang-Xiaodong1899** [comment]
@lucasjinreal Hi. Can you share the environment version? 
Such as Torch, DeepSpeed, transformers...

 Thanks a lot!

**Comment by lucasjinreal** [comment]
when did u got this error, during pretrain or instruction tuning?

**Comment by Wang-Xiaodong1899** [comment]
I tried to finetune the Qwen-VL model using LoRA, not the Qwen-VL chat version.

**Comment by lucasjinreal** [comment]
So you are sft on it, what's your text-image pair data? This part should be easy

**Comment by njucckevin** [comment]
> hi @supermancmk. I think you can delete this assert code line, because the query and key tensor are always same in the VisionAttention. However, skip this bug, I met another bug:
> 
> **File "/opt/conda/envs/qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 306, in fetch_sub_module assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary() AssertionError: {'id': 853, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}**
> 
> I found the related issues in DeepSpeed Repo, and I tried to back to `transformers=4.31.0` but it didn't work. Sad!

So why the `AssertionError: Only Support Self-Attention Currently` happened? In the same training script, this problem sometimes appears but sometimes disappears. Do you have any idea?

**Comment by hao-xyz** [comment]
> > hi @supermancmk. I think you can delete this assert code line, because the query and key tensor are always same in the VisionAttention. However, skip this bug, I met another bug:
> > **File "/opt/conda/envs/qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 306, in fetch_sub_module assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary() AssertionError: {'id': 853, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}**
> > I found the related issues in DeepSpeed Repo, and I tried to back to `transformers=4.31.0` but it didn't work. Sad!
> 
> So why the `AssertionError: Only Support Self-Attention Currently` happened? In the same training script, this problem sometimes appears but sometimes disappears. Do you have any idea?

hi, have you found the solution of this problem?
