### ISSUE TITLE
Clarification on Evaluation Settings

### ISSUE THREAD

**Issue by situozhang** [QwenLM/Qwen-VL#99]
Hi!
Congratulation for your great work! Invaluable contribution to the community!

I was hoping to gain some clarity on the evaluation settings. For the benchmarks that don't explicitly mention 0-shot evaluation, such as OKVQA, ChartVQA, is the model being **fine-tuned**? I couldn't find specific details on the testing process in the paper. Moreover, these dataset don't seem to appear during the multi-task pre-training stage.

Could you shed some light on this?

Thank you in advance for your assistance!

**Comment by ShuaiBai623** [comment]
In the multi-task pre-training stage, VQA data contains some of these data
